import SyncCore
import Testing

@testable import SyncSchemaGen

// The generator's sources, text for text: a registry's names and literal, the composing file, escapes a literal needs,
// the registries it refuses, and what a check finds stale.

struct SchemaSourcesTests {
  static let tiny: JSON = [
    "$schema": "./registry.schema.json", "registry": "tiny-log", "version": 1, "minVersion": 1,
    "products": ["tiny": ["surfaces": ["ios"]]],
    "types": [[
      "type": "default", "scope": "product:tiny", "identity": "keyed", "idPattern": #"^a\.b$"#, "life": false,
      "origins": ["replica"],
      "fields": ["title": ["kind": "lww", "writer": "client", "domain": ["type": "string", "enum": ["q\"b\\s\u{1}\u{E9}"]]]],
    ]],
    "commands": [["name": "tiny.in", "scope": "product:tiny", "origins": ["replica"], "serverInternal": false, "args": [:]]],
  ]

  @Test func aRegistryGeneratesItsNamesAndItsLiteralAndTheComposingFile() throws {
    let files = try SchemaSources.files(from: [RegistryFile(name: "tiny.registry.json", json: Self.tiny)])
    #expect(files == [
      GeneratedFile(name: "SyncSchema.swift", text: """
        // Generated by SyncSchemaGen from the product registries in packages/api-contract/sync. Do not edit.

        import SyncCore

        public enum SyncSchema {
          public static let registry = try! Registry(name: "windmill", composing: [
            Registry(json: TinyLog.registryFile),
          ])
          public static let version = registry.version
        }

        """),
      GeneratedFile(name: "TinyLog.generated.swift", text: #"""
        // Generated by SyncSchemaGen from packages/api-contract/sync/tiny.registry.json. Do not edit.

        import SyncCore

        public enum TinyLog {
          public enum Types {
            public static let `default` = "default"
          }

          public enum Commands {
            public static let `in` = "tiny.in"
          }

          static let registryFile: JSON = [
            "commands": [
              ["args": [:], "name": "tiny.in", "origins": ["replica"], "scope": "product:tiny", "serverInternal": false],
            ],
            "minVersion": 1,
            "products": ["tiny": ["surfaces": ["ios"]]],
            "registry": "tiny-log",
            "types": [
              [
                "fields": [
                  "title": ["domain": ["enum": ["q\"b\\s\u{1}\u{E9}"], "type": "string"], "kind": "lww", "writer": "client"],
                ],
                "idPattern": "^a\\.b$",
                "identity": "keyed",
                "life": false,
                "origins": ["replica"],
                "scope": "product:tiny",
                "type": "default",
              ],
            ],
            "version": 1,
          ]
        }

        """#),
    ])
  }

  @Test func aStringLiteralHoldsExactlyTheTextsScalars() {
    #expect(SwiftLiteral.string("a\"b\\c\n\u{0}\u{7F} e\u{301}\u{1F44D}\\(x)") == #""a\"b\\c\u{A}\u{0}\u{7F} e\u{301}\u{1F44D}\\(x)""#)
  }

  // A safe integer (at most 2^53 − 1) is an integer literal; every other number a float literal Swift reads back to the
  // same double.
  @Test func aNumberLiteralReadsBackToTheSameDouble() {
    let numbers: [Double] = [0, -500, 0.01, 1e-7, 9_007_199_254_740_992, 9_007_199_254_740_994, 1e21, 1.2345678901234568e20]
    #expect(numbers.map { SwiftLiteral.number(JSON.Number($0)!) } == [
      "0", "-500", "0.01", "1e-7", "9007199254740992.0", "9007199254740994.0", "1e+21", "123456789012345680000.0",
    ])
  }

  @Test(arguments: [
    ([JSON](), "no product registry in packages/api-contract/sync"),
    ([edited { $0["registry"] = "registry" }], "tiny.registry.json: the registry registry would declare the reserved enum Registry"),
    ([edited { $0["products"] = ["tiny": ["surfaces": ["ios"], "device": ["row": ["keyPattern": "^row$", "localOnly": false]]]] }],
     "tiny.registry.json does not round-trip through the registry decoder: it states a key the decoder drops, such as a default value"),
    ([edited { $0["version"] = 0 }], "tiny.registry.json: registry: JSON shape: expected an integer of at least 1, found 0"),
    ([tiny, edited { $0["registry"] = "other"; $0["version"] = 2; $0["products"] = ["other": [:]]; $0["types"] = []; $0["commands"] = [] }],
     "the product registries do not compose: tiny-log declares version 1 and minVersion 1, other 2 and 1: the registries composed declare one"),
    ([tiny, edited { $0["registry"] = "tiny-log"; $0["products"] = ["other": [:]]; $0["types"] = []; $0["commands"] = [] }],
     "tiny.registry.json declares a second enum TinyLog"),
  ])
  func aRegistryThatCannotGenerateIsRefusedNamingWhy(_ registries: [JSON], _ message: String) {
    let files = registries.enumerated().map { RegistryFile(name: $0.offset == 0 ? "tiny.registry.json" : "other.registry.json", json: $0.element) }
    let error = #expect(throws: GenerationError.self) { try SchemaSources.files(from: files) }
    #expect(error?.description == message)
  }

  // Byte for byte: a file whose text only looks the same (a KELVIN SIGN for a K) or is no UTF-8 at all is stale too.
  @Test func aCheckFindsEveryFileChangedMissingOrLeftOverByteForByte() {
    let generated = [
      GeneratedFile(name: "A.swift", text: "a"), GeneratedFile(name: "B.swift", text: "b"), GeneratedFile(name: "C.swift", text: "c"),
      GeneratedFile(name: "K.swift", text: "K"), GeneratedFile(name: "U.swift", text: "u"),
    ]
    let existing: [String: [UInt8]] = [
      "A.swift": Array("a".utf8), "B.swift": Array("b, edited".utf8), "K.swift": Array("\u{212A}".utf8), "U.swift": [0xFF],
      "Gone.generated.swift": Array("old".utf8),
    ]
    #expect(SchemaSources.stale(generated, existing: existing) == ["B.swift", "C.swift", "Gone.generated.swift", "K.swift", "U.swift"])
    #expect(SchemaSources.stale(generated, existing: Dictionary(uniqueKeysWithValues: generated.map { ($0.name, Array($0.text.utf8)) })) == [])
  }

  static func edited(_ edit: (inout JSON.Object) -> Void) -> JSON {
    var registry = try! tiny.asObject()
    edit(&registry)
    return .object(registry)
  }
}
