// Starter quest (F5 §03): a first season in a sailing dinghy, from rigging at
// the dock to a first solo sail — every safety drill genuinely gates going alone.

export default {
  id: 'learn-to-sail',
  title: 'Learn to sail',
  audience: 'life',
  estimate: 'a season',
  source: null,
  kinds: [
    { id: 'seamanship', hue: 'terracotta', label: 'Seamanship', description: 'Handling the boat under sail' },
    { id: 'knots', hue: 'olive', label: 'Knots', description: 'The ropework every sail depends on' },
    { id: 'weather', hue: 'sky', label: 'Weather', description: 'Reading wind, forecasts, and tides' },
    { id: 'safety', hue: 'brick', label: 'Safety', description: 'Drills that keep small trouble small' },
    { id: 'harbor', hue: 'gold', label: 'Harbor', description: 'Getting off the dock and back again' },
  ],
  nodes: [
    {
      id: 'rig-the-boat',
      label: 'Rig the boat and name its parts',
      color: 'terracotta',
      prerequisites: [],
      description: 'Take a dinghy from bare hull to ready: attach the sails, run the lines, and learn the name of every rope you touch. Your buoyancy aid goes on last, before the boat touches the water — it is part of rigging, not a separate decision. Done when you can rig without asking which line is which.',
    },
    {
      id: 'tie-the-working-knots',
      label: 'Tie the working knots',
      color: 'olive',
      prerequisites: ['rig-the-boat'],
      description: 'Learn the figure eight, bowline, cleat hitch, and round turn with two half hitches. Done when you can tie all four without looking.',
      links: ['https://www.animatedknots.com/'],
    },
    {
      id: 'steer-on-a-reach',
      label: 'Steer on a reach',
      color: 'terracotta',
      prerequisites: ['rig-the-boat'],
      description: 'Take the tiller with an instructor aboard and hold a straight line across the wind. Done when the boat goes where you point it and the sail stays quietly full.',
    },
    {
      id: 'read-the-wind-on-the-water',
      label: 'Read the wind on the water',
      color: 'sky',
      prerequisites: ['rig-the-boat'],
      description: 'Learn to spot gusts as dark ripples, watch the telltales, and always know where the wind is coming from. Done when you can point at the wind without checking a flag.',
    },
    {
      id: 'coil-and-heave-a-line',
      label: 'Coil and heave a line',
      color: 'olive',
      prerequisites: ['tie-the-working-knots'],
      description: 'Coil a line so it runs free and throw it cleanly to a dock or a swimmer. Done when it lands within reach of a helper on most throws.',
    },
    {
      id: 'tack-through-the-wind',
      label: 'Tack through the wind',
      color: 'terracotta',
      prerequisites: ['steer-on-a-reach'],
      description: 'Turn the bow through the wind and settle onto the new tack without stalling. Done when you can chain a dozen tacks upwind without losing speed.',
    },
    {
      id: 'find-the-points-of-sail',
      label: 'Find the points of sail',
      color: 'terracotta',
      prerequisites: ['steer-on-a-reach'],
      description: 'Sail every angle from close-hauled to a run and trim the sail to match. Done when you can set the sail right for any course without being told.',
    },
    {
      id: 'capsize-and-recover',
      label: 'Capsize on purpose and recover',
      color: 'brick',
      prerequisites: ['steer-on-a-reach'],
      description: 'Tip the boat over in warm water, buoyancy aid on and an instructor alongside, then right it and climb back in. Done when going over feels like a routine instead of an emergency — this is what makes sailing alone sane.',
    },
    {
      id: 'pick-a-weather-window',
      label: 'Pick a weather window',
      color: 'sky',
      prerequisites: ['read-the-wind-on-the-water'],
      description: 'Read a marine forecast the night before and decide whether tomorrow is a sailing day. Done when you have called it right a handful of times, including the days you chose to stay ashore.',
    },
    {
      id: 'gybe-with-control',
      label: 'Gybe with control',
      color: 'terracotta',
      prerequisites: ['tack-through-the-wind'],
      description: 'Bring the stern through the wind on purpose, with the boom crossing when you choose. Done when a gybe feels like a decision, not a surprise.',
    },
    {
      id: 'run-a-man-overboard-drill',
      label: 'Run a crew-overboard drill',
      color: 'brick',
      prerequisites: ['tack-through-the-wind'],
      description: 'Practice the figure-eight return: sail away, come back on a controlled reach, and stop beside a floating cushion. Done when you can pick it up on the first pass, three times in a row.',
    },
    {
      id: 'learn-the-right-of-way-rules',
      label: 'Learn the right-of-way rules',
      color: 'brick',
      prerequisites: ['find-the-points-of-sail'],
      description: 'Learn who gives way: port tack to starboard, windward boat to leeward, and everyone to whoever they overtake. Done when you can name the give-way boat in any crossing without pausing to think.',
    },
    {
      id: 'read-the-local-tides',
      label: 'Read the local tides',
      color: 'sky',
      prerequisites: ['pick-a-weather-window'],
      description: 'Look up tide times and heights for your home water and learn how the current runs through the day. Done when you know, before leaving home, which way the water will be moving.',
    },
    {
      id: 'leave-the-dock-under-sail',
      label: 'Leave the dock under sail',
      color: 'gold',
      prerequisites: ['steer-on-a-reach', 'tie-the-working-knots'],
      description: 'Cast off your own lines, fend off, and sail cleanly away from the dock. Done when you can pick your moment and slip out on the first try.',
    },
    {
      id: 'come-alongside-and-dock',
      label: 'Come alongside and dock',
      color: 'gold',
      prerequisites: ['leave-the-dock-under-sail', 'find-the-points-of-sail', 'coil-and-heave-a-line'],
      description: 'Approach into the wind, ease the sail to slow down, and arrive at the dock at walking pace. Done when your landings are gentle enough that nobody reaches out to fend you off.',
    },
    {
      id: 'sail-a-triangle-course',
      label: 'Sail a triangle course',
      color: 'terracotta',
      prerequisites: ['tack-through-the-wind', 'gybe-with-control', 'find-the-points-of-sail'],
      description: 'Sail a full triangle — a beat upwind, a reach, and a run home — rounding each mark cleanly. Done when you can lap the course twice without an instructor saying a word.',
    },
    {
      id: 'take-your-first-solo-sail',
      label: 'Take your first solo sail',
      color: 'terracotta',
      prerequisites: [
        'sail-a-triangle-course',
        'capsize-and-recover',
        'run-a-man-overboard-drill',
        'come-alongside-and-dock',
        'pick-a-weather-window',
        'read-the-local-tides',
        'learn-the-right-of-way-rules',
      ],
      description: 'Choose a gentle, well-forecast day, tell someone ashore your plan and return time, and take the boat out alone. Done when you are back at the dock with the boat put away, grinning.',
    },
  ],
};
