export default {
  id: 'ml-foundations',
  title: 'ML foundations',
  audience: 'dev',
  estimate: '~6 months',
  source: 'roadmap.sh (CC BY-SA)',
  kinds: [
    { id: 'theory', hue: 'plum', label: 'Theory', description: 'The ideas and math under every model' },
    { id: 'data', hue: 'sky', label: 'Data', description: 'Finding, cleaning, and understanding real data' },
    { id: 'practice', hue: 'terracotta', label: 'Practice', description: 'Models you build, train, and evaluate yourself' },
  ],
  nodes: [
    {
      id: 'what-a-model-is',
      label: 'Learn what a model really is',
      color: 'plum',
      prerequisites: [],
      description: 'Supervised versus unsupervised learning, features and labels, loss, and the train/test split — the frame everything else hangs on. Done when you have written a paragraph explaining to a friend how a spam filter learns.',
      links: ['https://developers.google.com/machine-learning/crash-course'],
    },
    {
      id: 'python-and-notebooks',
      label: 'Set up Python and notebooks',
      color: 'terracotta',
      prerequisites: ['what-a-model-is'],
      description: 'Install Python, get a Jupyter notebook running, and learn your way around the cells. Done when you can load a file, loop over it, and plot something rough.',
    },
    {
      id: 'linear-algebra',
      label: 'Refresh vectors and matrices',
      color: 'plum',
      prerequisites: ['what-a-model-is'],
      description: 'Vectors, matrices, dot products, and matrix multiplication as transformation. Done when you can say what a dot product measures without reciting a formula.',
      links: ['https://www.3blue1brown.com/topics/linear-algebra'],
    },
    {
      id: 'probability-and-stats',
      label: 'Refresh probability and statistics',
      color: 'plum',
      prerequisites: ['what-a-model-is'],
      description: 'Distributions, expectation and variance, and conditional probability. Done when Bayes\' rule feels like common sense written down.',
      links: ['https://www.khanacademy.org/math/statistics-probability'],
    },
    {
      id: 'calculus-gradients',
      label: 'Understand derivatives and gradients',
      color: 'plum',
      prerequisites: ['linear-algebra'],
      description: 'Derivatives as sensitivity, the chain rule, and the gradient as the direction of steepest ascent. Done when you can explain why models learn by walking downhill.',
      links: ['https://www.3blue1brown.com/topics/calculus'],
    },
    {
      id: 'numpy',
      label: 'Compute with NumPy arrays',
      color: 'terracotta',
      prerequisites: ['python-and-notebooks', 'linear-algebra'],
      description: 'Arrays as vectors and matrices, broadcasting, and vectorized math. Done when you can replace a nested loop with one array expression.',
    },
    {
      id: 'pandas',
      label: 'Wrangle tables with pandas',
      color: 'sky',
      prerequisites: ['python-and-notebooks'],
      description: 'DataFrames, filtering, joins, and groupby on real CSV files. Done when a question about a dataset turns into three lines, not thirty.',
      links: ['https://pandas.pydata.org/docs/user_guide/10min.html'],
    },
    {
      id: 'visualization',
      label: 'See your data before you model it',
      color: 'sky',
      prerequisites: ['pandas'],
      description: 'Histograms, scatter plots, and box plots with matplotlib or seaborn. Done when your first move with new data is to draw it.',
    },
    {
      id: 'data-cleaning',
      label: 'Clean a messy dataset',
      color: 'sky',
      prerequisites: ['pandas'],
      description: 'Missing values, duplicates, wrong dtypes, and outliers — with your decisions written down. Done when someone could rerun your cleaning and get the same table.',
    },
    {
      id: 'exploratory-analysis',
      label: 'Run a full exploratory analysis',
      color: 'sky',
      prerequisites: ['visualization', 'data-cleaning'],
      description: 'Take one real dataset from raw to understood: distributions, relationships, oddities, and open questions. Done when your notebook tells a story a colleague could follow.',
    },
    {
      id: 'linear-regression',
      label: 'Learn linear regression deeply',
      color: 'plum',
      prerequisites: ['calculus-gradients'],
      description: 'The model, mean squared error, and how gradient descent finds the weights. Done when you can derive the update step for one weight by hand.',
    },
    {
      id: 'regression-from-scratch',
      label: 'Code linear regression from scratch',
      color: 'terracotta',
      prerequisites: ['linear-regression', 'numpy'],
      description: 'Implement the loss and gradient descent in NumPy, no libraries, and fit a real dataset. Done when your loss curve falls and your line matches the data.',
    },
    {
      id: 'classification',
      label: 'Learn logistic regression',
      color: 'plum',
      prerequisites: ['linear-regression', 'probability-and-stats'],
      description: 'From predicting numbers to predicting classes: sigmoid, decision boundaries, and cross-entropy loss. Done when you can say why squared error is the wrong loss here.',
    },
    {
      id: 'evaluation-metrics',
      label: 'Judge models with honest metrics',
      color: 'plum',
      prerequisites: ['classification'],
      description: 'Accuracy and its failure modes, precision, recall, confusion matrices, and validation splits. Done when 99 percent accuracy makes you suspicious, not satisfied.',
    },
    {
      id: 'overfitting',
      label: 'Understand overfitting and bias',
      color: 'plum',
      prerequisites: ['evaluation-metrics'],
      description: 'Bias versus variance, why models memorize, and regularization as the cure. Done when you can diagnose overfitting from a pair of learning curves.',
    },
    {
      id: 'sklearn-workflow',
      label: 'Train models with scikit-learn',
      color: 'terracotta',
      prerequisites: ['regression-from-scratch', 'data-cleaning'],
      description: 'The fit/predict workflow, pipelines, and proper train/validation discipline on a real dataset. Done when trying a new model type takes minutes, not days.',
      links: ['https://scikit-learn.org/stable/getting_started.html'],
    },
    {
      id: 'feature-engineering',
      label: 'Engineer features that help',
      color: 'sky',
      prerequisites: ['sklearn-workflow'],
      description: 'Encode categoricals, scale numbers, and create features from domain sense. Done when one engineered feature measurably beats the raw baseline.',
    },
    {
      id: 'trees-and-ensembles',
      label: 'Learn trees and ensembles',
      color: 'plum',
      prerequisites: ['overfitting'],
      description: 'Decision trees, then random forests and gradient boosting — why averaging many weak models tames variance. Done when you can explain what makes boosting different from bagging.',
    },
    {
      id: 'kaggle-entry',
      label: 'Enter a beginner Kaggle contest',
      color: 'terracotta',
      prerequisites: ['feature-engineering', 'trees-and-ensembles'],
      description: 'Pick a starter competition, build a clean pipeline, and climb from your first score. Done when you have made three submissions that each beat the last.',
      links: ['https://www.kaggle.com/competitions'],
    },
    {
      id: 'neural-networks',
      label: 'Learn how neural networks work',
      color: 'plum',
      prerequisites: ['classification'],
      description: 'Stack logistic units into layers: activations, forward passes, and backpropagation as the chain rule at scale. Done when backprop on a tiny net is arithmetic you can do on paper.',
      links: ['https://www.3blue1brown.com/topics/neural-networks'],
    },
    {
      id: 'nn-from-scratch',
      label: 'Build a neural net from scratch',
      color: 'terracotta',
      prerequisites: ['neural-networks', 'regression-from-scratch'],
      description: 'A small multilayer network in NumPy with hand-written backprop. Done when it learns XOR or a digit subset and you trust every line.',
    },
    {
      id: 'pytorch',
      label: 'Move to PyTorch',
      color: 'terracotta',
      prerequisites: ['nn-from-scratch'],
      description: 'Tensors, autograd, and the training loop — rebuild your scratch network in a real framework. Done when autograd feels like a tool you understand, not magic you rent.',
      links: ['https://pytorch.org/tutorials/beginner/basics/intro.html'],
    },
    {
      id: 'image-classifier',
      label: 'Train a real image classifier',
      color: 'terracotta',
      prerequisites: ['pytorch', 'evaluation-metrics'],
      description: 'Train on MNIST or CIFAR-10 with proper splits, track validation metrics, and beat a sane baseline. Done when you can show your accuracy claim is honest.',
    },
    {
      id: 'own-dataset',
      label: 'Assemble a dataset of your own',
      color: 'sky',
      prerequisites: ['exploratory-analysis'],
      description: 'Collect data about a question you actually care about — scrape it, export it, or log it — and document where it came from. Done when it is clean enough to model.',
    },
    {
      id: 'capstone',
      label: 'Run an end-to-end capstone',
      color: 'terracotta',
      prerequisites: ['own-dataset', 'kaggle-entry', 'image-classifier'],
      description: 'Your dataset, your question: clean, explore, model, evaluate, and write up what you found. Done when the write-up states what worked, what did not, and why.',
    },
    {
      id: 'unsupervised',
      label: 'Learn clustering and PCA',
      color: 'plum',
      prerequisites: ['linear-algebra', 'probability-and-stats'],
      description: 'Finding structure without labels: k-means, and PCA as finding the directions that matter. Done when you can say what the first principal component of a dataset means.',
    },
  ],
};
