export default {
  id: 'frontend-path',
  title: 'Frontend path',
  audience: 'dev',
  estimate: '~4-6 months',
  source: 'roadmap.sh (CC BY-SA)',
  kinds: [
    { id: 'build', hue: 'terracotta', label: 'Build', description: 'Projects you make with your own hands' },
    { id: 'learn', hue: 'olive', label: 'Learn', description: 'Concepts and tools you pick up along the way' },
    { id: 'ship', hue: 'gold', label: 'Ship', description: 'Real work, live on the internet, in front of people' },
  ],
  nodes: [
    {
      id: 'hand-write-a-page',
      label: 'Hand-write a page in plain HTML',
      color: 'terracotta',
      prerequisites: [],
      description: 'Open a text editor, write an index.html with headings, paragraphs, and a link, and open it in your browser. Done when you see your own words rendered on a page you made.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development'],
    },
    {
      id: 'how-the-web-works',
      label: 'Learn how the web serves a page',
      color: 'olive',
      prerequisites: ['hand-write-a-page'],
      description: 'Follow a URL from address bar to rendered page: DNS, HTTP requests and responses, and what the browser does with the answer. Done when you can narrate that round trip from memory.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development/Getting_started/Web_standards/How_the_web_works'],
    },
    {
      id: 'semantic-html',
      label: 'Structure pages with semantic HTML',
      color: 'olive',
      prerequisites: ['hand-write-a-page'],
      description: 'Go past divs: headings, nav, main, forms, images, and tables — the tags that say what content is. Done when you can mark up an article so it reads cleanly with CSS turned off.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Structuring_content'],
    },
    {
      id: 'css-fundamentals',
      label: 'Learn CSS selectors and the box model',
      color: 'olive',
      prerequisites: ['hand-write-a-page'],
      description: 'Selectors, the cascade, specificity, and the box model — how the browser decides what every element looks like. Done when padding versus margin holds no surprises.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Styling_basics'],
    },
    {
      id: 'js-fundamentals',
      label: 'Learn JavaScript fundamentals',
      color: 'olive',
      prerequisites: ['hand-write-a-page'],
      description: 'Variables, functions, arrays, objects, loops, and conditionals, practiced in the browser console. Done when you can solve small problems without copying code you don\'t understand.',
      links: ['https://javascript.info'],
    },
    {
      id: 'git-basics',
      label: 'Put your work under git',
      color: 'olive',
      prerequisites: ['hand-write-a-page'],
      description: 'Install git, make a repository for your pages, and get comfortable with add, commit, branch, and push to GitHub. Done when committing is a reflex, not a ceremony.',
      links: ['https://git-scm.com/book/en/v2'],
    },
    {
      id: 'style-a-page',
      label: 'Style a real page from scratch',
      color: 'terracotta',
      prerequisites: ['semantic-html', 'css-fundamentals'],
      description: 'Pick a simple site you admire and rebuild its look over your own HTML — type, color, spacing. Done when a screenshot of yours could pass for the original at a glance.',
    },
    {
      id: 'flexbox-and-grid',
      label: 'Lay out pages with flexbox and grid',
      color: 'olive',
      prerequisites: ['css-fundamentals'],
      description: 'The two layout systems that ended the era of float hacks. Done when you can center anything on purpose and build a card grid without peeking at references.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/CSS_layout'],
    },
    {
      id: 'responsive-design',
      label: 'Make layouts respond to any screen',
      color: 'olive',
      prerequisites: ['flexbox-and-grid'],
      description: 'Mobile-first thinking, relative units, and media queries. Done when your page reads comfortably at phone, tablet, and desktop widths without horizontal scroll.',
      links: ['https://web.dev/learn/design'],
    },
    {
      id: 'personal-site',
      label: 'Build your personal site',
      color: 'terracotta',
      prerequisites: ['style-a-page', 'responsive-design'],
      description: 'A small site about you: who you are, what you are building, and how to reach you. Done when it looks intentional on both a phone and a laptop.',
    },
    {
      id: 'ship-first-site',
      label: 'Put your site on the internet',
      color: 'gold',
      prerequisites: ['personal-site', 'git-basics'],
      description: 'Deploy the site straight from your repository with GitHub Pages or Netlify. Done when a friend can open your URL on their phone.',
    },
    {
      id: 'dom-manipulation',
      label: 'Script the page with the DOM',
      color: 'olive',
      prerequisites: ['js-fundamentals', 'semantic-html'],
      description: 'Select elements, listen for events, and change the page in response. Done when you can make a button do something interesting without a framework.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Scripting'],
    },
    {
      id: 'interactive-widget',
      label: 'Build an interactive widget',
      color: 'terracotta',
      prerequisites: ['dom-manipulation', 'css-fundamentals'],
      description: 'Tabs, a modal, an image carousel, or a to-do list in plain HTML, CSS, and JavaScript. Done when it works, looks decent, and survives fast clicking.',
    },
    {
      id: 'async-and-fetch',
      label: 'Fetch data with async JavaScript',
      color: 'olive',
      prerequisites: ['js-fundamentals', 'how-the-web-works'],
      description: 'Promises, async/await, and the fetch API — asking a server for JSON and handling the wait. Done when loading and error states are as deliberate as the happy path.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development/Extensions/Async_JS'],
    },
    {
      id: 'api-app',
      label: 'Build an app on a public API',
      color: 'terracotta',
      prerequisites: ['async-and-fetch', 'dom-manipulation'],
      description: 'A weather app, a movie finder — anything that fetches real data and renders it. Done when it handles a slow network and a bad search without falling over.',
    },
    {
      id: 'accessibility',
      label: 'Make your pages accessible',
      color: 'olive',
      prerequisites: ['semantic-html'],
      description: 'Alt text, labels, contrast, focus order, and keyboard navigation. Done when you can drive your own site without touching the mouse.',
      links: ['https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Accessibility'],
    },
    {
      id: 'npm-and-tooling',
      label: 'Set up Node, npm, and a bundler',
      color: 'olive',
      prerequisites: ['js-fundamentals'],
      description: 'Install Node, understand package.json, and scaffold a project with Vite. Done when you can add a dependency and explain what npm actually did.',
    },
    {
      id: 'react-fundamentals',
      label: 'Learn React components and state',
      color: 'olive',
      prerequisites: ['npm-and-tooling', 'dom-manipulation'],
      description: 'Components, props, state, and rendering lists — the mental model behind most frontend work today. Done when you can explain what a re-render is and what triggers one.',
      links: ['https://react.dev/learn'],
    },
    {
      id: 'react-app',
      label: 'Build a small React app',
      color: 'terracotta',
      prerequisites: ['react-fundamentals', 'async-and-fetch'],
      description: 'A multi-page app with routing, fetched data, and shared state — a recipe box, a habit tracker. Done when adding a feature no longer means rethinking the structure.',
    },
    {
      id: 'testing-basics',
      label: 'Learn to write automated tests',
      color: 'olive',
      prerequisites: ['npm-and-tooling'],
      description: 'Unit tests with Vitest: arrange, act, assert, and run them on every change. Done when a test catches a bug for you before the browser does.',
    },
    {
      id: 'open-source-pr',
      label: 'Send your first open source PR',
      color: 'gold',
      prerequisites: ['git-basics', 'dom-manipulation'],
      description: 'Find a small issue on a project you use, fix it, open the pull request, and stay with the review that comes back. Done when it is submitted and every review comment has an answer or a commit — whether it merges is the maintainer\'s call, not yours.',
    },
    {
      id: 'test-your-app',
      label: 'Put your React app under test',
      color: 'terracotta',
      prerequisites: ['react-app', 'testing-basics'],
      description: 'Add component and logic tests around the riskiest behavior in your app. Done when you can refactor with the suite green and your pulse steady.',
    },
    {
      id: 'portfolio',
      label: 'Assemble your portfolio',
      color: 'terracotta',
      prerequisites: ['react-app', 'api-app'],
      description: 'Curate your three best projects with short write-ups: what it is, what was hard, what you would change. Done when each project has a live link and a readable README.',
    },
    {
      id: 'ship-portfolio',
      label: 'Ship your portfolio for real',
      color: 'gold',
      prerequisites: ['portfolio', 'accessibility'],
      description: 'Deploy the portfolio, run an accessibility and performance pass over it, and share it where developers will see it. Done when it is the link in your bio.',
    },
  ],
};
