export default {
  id: 'personal-finance-reset',
  title: 'Personal finance reset',
  audience: 'life',
  estimate: '~1 month',
  source: null,
  kinds: [
    { id: 'habits', hue: 'olive', label: 'Habits', description: 'Small money rituals you repeat until they hold' },
    { id: 'systems', hue: 'sky', label: 'Systems', description: 'One-time setups that keep working after you stop' },
  ],
  nodes: [
    {
      id: 'balance-page',
      label: 'Write down every balance you have',
      color: 'olive',
      prerequisites: [],
      description: 'Log into every account you have — checking, savings, cards, anything with money in it — and write today\'s balance for each on one page. Done is a dated page with no account missing.',
    },
    {
      id: 'pull-statements',
      label: 'Pull one full month of statements',
      color: 'sky',
      prerequisites: ['balance-page'],
      description: 'Collect last month\'s statement from every account on your balance page into one folder. Done when every account has its month in there.',
    },
    {
      id: 'weekly-half-hour',
      label: 'Book a weekly money half-hour',
      color: 'olive',
      prerequisites: ['balance-page'],
      description: 'Put a recurring thirty minutes on your calendar to redo the balance page and skim the week\'s spending. Done when it\'s booked and you\'ve kept the first one.',
    },
    {
      id: 'list-last-month',
      label: 'List where last month actually went',
      color: 'sky',
      prerequisites: ['pull-statements'],
      description: 'Go through the statements line by line and write every outflow into one list, no matter how small. Done when the list adds up to what actually left your accounts.',
    },
    {
      id: 'recurring-charges',
      label: 'List every recurring charge',
      color: 'sky',
      prerequisites: ['pull-statements'],
      description: 'Comb the statements for anything that charges on repeat — subscriptions, memberships, auto-renewals. Done is one list with each amount and its renewal date.',
    },
    {
      id: 'honest-buckets',
      label: 'Sort the month into honest buckets',
      color: 'sky',
      prerequisites: ['list-last-month'],
      description: 'Group the list into six to eight categories named after how you actually live, not how a textbook says you should. Done when every line has a bucket and none of them is called misc.',
    },
    {
      id: 'keep-or-cut',
      label: 'Mark each recurring charge keep or cut',
      color: 'sky',
      prerequisites: ['recurring-charges'],
      description: 'Go down the recurring list and decide each one: keep it or cut it, then actually cancel the cuts. Done when every line is marked and the cancellations are confirmed.',
    },
    {
      id: 'bucket-numbers',
      label: 'Give every bucket next month\'s number',
      color: 'sky',
      prerequisites: ['honest-buckets', 'keep-or-cut'],
      description: 'Using what each bucket really got last month, decide what it gets next month — some go up, some go down. Done when every bucket has a number you believe.',
    },
    {
      id: 'automate-payday',
      label: 'Automate one payday move you chose',
      color: 'sky',
      prerequisites: ['bucket-numbers'],
      description: 'Pick the one transfer from your plan that matters most — into savings, toward a debt, into the bills account — and schedule it to happen on payday without you. Done when the first run has a date.',
    },
    {
      id: 'week-on-the-numbers',
      label: 'Live one week on the numbers',
      color: 'olive',
      prerequisites: ['bucket-numbers'],
      description: 'Spend a normal week keeping each bucket inside its number, noting where it pinches. Done when the week is over and the notes exist, whatever the score.',
    },
    {
      id: 'close-the-month',
      label: 'Close the month and reset the numbers',
      color: 'olive',
      prerequisites: ['week-on-the-numbers', 'weekly-half-hour'],
      description: 'In the last money half-hour of the month, redo the balance page, compare each bucket to its number, and write next month\'s numbers. Done when next month starts with a plan you\'ve already adjusted once.',
    },
  ],
};
