import fs from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

// Serves the two sheets the plain HTML pages in public/ link — /fonts.css cut from @fontsource,
// /chrome.css beside this file — by middleware in dev and emitted into dist at build.
const FONTS = [
  { pkg: 'baloo-2', subsets: ['latin', 'latin-ext'], weights: [600, 700, 800] },
  { pkg: 'nunito', subsets: ['latin', 'latin-ext'], weights: [400, 700, 800] },
  { pkg: 'jetbrains-mono', subsets: ['latin'], weights: [400, 600, 700] },
];

// Every page in public/ but the undressed ones must link both sheets.
const PAGES = new URL('../public/', import.meta.url);
const UNDRESSED = ['pricing-preview.html'];

export function staticPageAssets() {
  const woff2 = new Map();
  const faces = [];

  for (const font of FONTS) {
    for (const weight of font.weights) {
      // Read the per-weight aggregate sheet: the per-subset entry files omit unicode-range.
      const sheet = fs.readFileSync(require.resolve(`@fontsource/${font.pkg}/${weight}.css`), 'utf8');
      for (const subset of font.subsets) {
        const file = `${font.pkg}-${subset}-${weight}-normal.woff2`;
        const declared = sheet.split('@font-face').find((block) => block.includes(file));
        if (!declared) {
          throw new Error(`@fontsource/${font.pkg} no longer ships ${file} — /fonts.css would quietly lose a weight`);
        }
        const family = /font-family:\s*([^;]+);/.exec(declared)[1];
        const range = /unicode-range:\s*([^;]+);/.exec(declared);
        woff2.set(file, require.resolve(`@fontsource/${font.pkg}/files/${file}`));
        faces.push([
          '@font-face {',
          `  font-family: ${family};`,
          '  font-style: normal;',
          '  font-display: swap;',
          `  font-weight: ${weight};`,
          `  src: url(/fonts/${file}) format('woff2');`,
          ...(range ? [`  unicode-range: ${range[1]};`] : []),
          '}',
        ].join('\n'));
      }
    }
  }

  const sheets = new Map([
    ['fonts.css', `/* Generated by scripts/staticPageAssets.js from @fontsource — do not edit, do not commit. */\n${faces.join('\n\n')}\n`],
    ['chrome.css', fs.readFileSync(new URL('./staticPageChrome.css', import.meta.url), 'utf8')],
  ]);

  for (const page of fs.readdirSync(PAGES).filter((name) => name.endsWith('.html'))) {
    if (UNDRESSED.includes(page)) continue;
    const html = fs.readFileSync(new URL(page, PAGES), 'utf8');
    const missing = [...sheets.keys()].filter((sheet) => !html.includes(`href="/${sheet}"`));
    if (missing.length) {
      throw new Error(`public/${page} does not link ${missing.map((s) => `/${s}`).join(' or ')} — it would render outside the family`);
    }

    const canonical = /<link rel="canonical" href="([^"]+)"/.exec(html)?.[1];
    const noindex = /<meta name="robots" content="[^"]*noindex/.test(html);
    if (!canonical && !noindex) {
      throw new Error(`public/${page} names no canonical and is not noindex — the sitemap is built from these, so the page would ship unlisted`);
    }
    if (noindex) continue;

    const title = /<title>([^<]*)<\/title>/.exec(html)?.[1];
    const description = /<meta name="description" content="([^"]*)"/.exec(html)?.[1];
    const said = (attribute, value) => html.includes(`${attribute} content="${value}" />`);
    const wrong = [
      ['og:title', 'property="og:title"', title],
      ['og:description', 'property="og:description"', description],
      ['og:url', 'property="og:url"', canonical],
      ['twitter:title', 'name="twitter:title"', title],
      ['twitter:description', 'name="twitter:description"', description],
    ].filter(([, attribute, value]) => !value || !said(attribute, value));
    if (wrong.length || !html.includes('name="twitter:card"') || !html.includes('property="og:image"')) {
      throw new Error(`public/${page} unfurls as something other than itself — ${wrong.map(([tag]) => tag).join(', ') || 'no twitter:card or og:image'}. og/twitter must repeat this page's own <title>, description and canonical`);
    }
  }

  return {
    name: 'windmill:static-page-assets',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = (req.url || '').split('?')[0];
        const sheet = sheets.get(url.slice(1));
        if (sheet) {
          res.setHeader('content-type', 'text/css; charset=utf-8');
          res.end(sheet);
          return;
        }
        const source = url.startsWith('/fonts/') ? woff2.get(url.slice('/fonts/'.length)) : null;
        if (!source) {
          next();
          return;
        }
        res.setHeader('content-type', 'font/woff2');
        res.end(fs.readFileSync(source));
      });
    },
    generateBundle() {
      for (const [fileName, source] of sheets) {
        this.emitFile({ type: 'asset', fileName, source });
      }
      for (const [file, source] of woff2) {
        this.emitFile({ type: 'asset', fileName: `fonts/${file}`, source: fs.readFileSync(source) });
      }
    },
  };
}
