import fs from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(import.meta.url);

// The pages in public/ are plain HTML — they never enter Vite's module graph, so nothing the SPA
// entry pulls in ever reaches them. That cost them both of the things a page needs before it is
// recognisably Windmill: the @fontsource faces src/styles/fonts.js imports (every page declared
// --font-display: 'Baloo 2' and rendered in a system fallback), and the family chrome (every page
// carried its own pasted copy, under a comment admitting they had to be edited together). This
// plugin serves the two sheets they link instead — /fonts.css cut from the very packages the SPA
// imports, /chrome.css authored beside this file — by middleware in dev and emitted into dist at
// build. No binaries in the source tree, and one geometry that cannot drift.
//
// Only the faces those pages actually paint: Baloo 2 600/700/800 (pricing's meter count and price
// sit at 800), Nunito 400/700/800, JetBrains Mono 400/600/700 (pricing's eyebrow, connect's
// snippet labels). Mono is ASCII-only here, so it needs no latin-ext.
const FONTS = [
  { pkg: 'baloo-2', subsets: ['latin', 'latin-ext'], weights: [600, 700, 800] },
  { pkg: 'nunito', subsets: ['latin', 'latin-ext'], weights: [400, 700, 800] },
  { pkg: 'jetbrains-mono', subsets: ['latin'], weights: [400, 600, 700] },
];

// pricing-preview.html is a meta-refresh stub with two lines of body — the one page in public/
// with no chrome to wear. Every other page must link both sheets, or it silently drops off the
// family the moment someone adds it.
const PAGES = new URL('../public/', import.meta.url);
const UNDRESSED = ['pricing-preview.html'];

export function staticPageAssets() {
  const woff2 = new Map();
  const faces = [];

  for (const font of FONTS) {
    for (const weight of font.weights) {
      // The per-weight aggregate sheet is the one carrying unicode-range; fontsource's per-subset
      // entry files omit it, which would let latin-ext shadow latin for the whole alphabet.
      const sheet = fs.readFileSync(require.resolve(`@fontsource/${font.pkg}/${weight}.css`), 'utf8');
      for (const subset of font.subsets) {
        const file = `${font.pkg}-${subset}-${weight}-normal.woff2`;
        const declared = sheet.split('@font-face').find((block) => block.includes(file));
        if (!declared) {
          throw new Error(`@fontsource/${font.pkg} no longer ships ${file} — /fonts.css would quietly lose a weight`);
        }
        const family = /font-family:\s*([^;]+);/.exec(declared)[1];
        const range = /unicode-range:\s*([^;]+);/.exec(declared);
        woff2.set(file, require.resolve(`@fontsource/${font.pkg}/files/${file}`));
        faces.push([
          '@font-face {',
          `  font-family: ${family};`,
          '  font-style: normal;',
          '  font-display: swap;',
          `  font-weight: ${weight};`,
          `  src: url(/fonts/${file}) format('woff2');`,
          ...(range ? [`  unicode-range: ${range[1]};`] : []),
          '}',
        ].join('\n'));
      }
    }
  }

  const sheets = new Map([
    ['fonts.css', `/* Generated by scripts/staticPageAssets.js from @fontsource — do not edit, do not commit. */\n${faces.join('\n\n')}\n`],
    ['chrome.css', fs.readFileSync(new URL('./staticPageChrome.css', import.meta.url), 'utf8')],
  ]);

  for (const page of fs.readdirSync(PAGES).filter((name) => name.endsWith('.html'))) {
    if (UNDRESSED.includes(page)) continue;
    const html = fs.readFileSync(new URL(page, PAGES), 'utf8');
    const missing = [...sheets.keys()].filter((sheet) => !html.includes(`href="/${sheet}"`));
    if (missing.length) {
      throw new Error(`public/${page} does not link ${missing.map((s) => `/${s}`).join(' or ')} — it would render outside the family`);
    }

    // The head a crawler and a chat window read. Two rules, both about the same drift: a page
    // that names no canonical cannot be put in the sitemap (which is generated from these
    // canonicals — scripts/build-landing-shells.mjs), and og/twitter must keep saying exactly
    // what <title> and the description say, or the link unfurls as a page we stopped shipping.
    // A noindex page (404, pause, the pricing stub) is exempt from the unfurl half: it is not a
    // destination, it is what a visitor gets instead of one.
    const canonical = /<link rel="canonical" href="([^"]+)"/.exec(html)?.[1];
    const noindex = /<meta name="robots" content="[^"]*noindex/.test(html);
    if (!canonical && !noindex) {
      throw new Error(`public/${page} names no canonical and is not noindex — the sitemap is built from these, so the page would ship unlisted`);
    }
    if (noindex) continue;

    const title = /<title>([^<]*)<\/title>/.exec(html)?.[1];
    const description = /<meta name="description" content="([^"]*)"/.exec(html)?.[1];
    const said = (attribute, value) => html.includes(`${attribute} content="${value}" />`);
    const wrong = [
      ['og:title', 'property="og:title"', title],
      ['og:description', 'property="og:description"', description],
      ['og:url', 'property="og:url"', canonical],
      ['twitter:title', 'name="twitter:title"', title],
      ['twitter:description', 'name="twitter:description"', description],
    ].filter(([, attribute, value]) => !value || !said(attribute, value));
    if (wrong.length || !html.includes('name="twitter:card"') || !html.includes('property="og:image"')) {
      throw new Error(`public/${page} unfurls as something other than itself — ${wrong.map(([tag]) => tag).join(', ') || 'no twitter:card or og:image'}. og/twitter must repeat this page's own <title>, description and canonical`);
    }
  }

  return {
    name: 'windmill:static-page-assets',
    configureServer(server) {
      server.middlewares.use((req, res, next) => {
        const url = (req.url || '').split('?')[0];
        const sheet = sheets.get(url.slice(1));
        if (sheet) {
          res.setHeader('content-type', 'text/css; charset=utf-8');
          res.end(sheet);
          return;
        }
        const source = url.startsWith('/fonts/') ? woff2.get(url.slice('/fonts/'.length)) : null;
        if (!source) {
          next();
          return;
        }
        res.setHeader('content-type', 'font/woff2');
        res.end(fs.readFileSync(source));
      });
    },
    generateBundle() {
      for (const [fileName, source] of sheets) {
        this.emitFile({ type: 'asset', fileName, source });
      }
      for (const [file, source] of woff2) {
        this.emitFile({ type: 'asset', fileName: `fonts/${file}`, source: fs.readFileSync(source) });
      }
    },
  };
}
