// @ts-check

import { Id } from '../../../platform/domain-kit/entities.js';
import { Exercise, ExerciseValue } from './catalogue.js';

/** @type {readonly ExerciseValue[] | null} */
let seeds = null;

export const SeedExercises = Object.freeze({
  get all() {
    if (seeds === null) seeds = Object.freeze([
      new ExerciseValue(new Id('back-squat', Exercise), 'Back Squat', 'squat', 'barbell', 2.5),
      new ExerciseValue(new Id('front-squat', Exercise), 'Front Squat', 'squat', 'barbell', 2.5),
      new ExerciseValue(new Id('goblet-squat', Exercise), 'Goblet Squat', 'squat', 'dumbbell', 2.0),
      new ExerciseValue(new Id('bulgarian-split-squat', Exercise), 'Bulgarian Split Squat', 'squat', 'dumbbell', 2.0),
      new ExerciseValue(new Id('walking-lunge', Exercise), 'Walking Lunge', 'squat', 'dumbbell', 2.0),
      new ExerciseValue(new Id('step-up', Exercise), 'Step Up', 'squat', 'dumbbell', 2.0),
      new ExerciseValue(new Id('leg-press', Exercise), 'Leg Press', 'squat', 'machine', 5.0),
      new ExerciseValue(new Id('hack-squat', Exercise), 'Hack Squat', 'squat', 'machine', 5.0),
      new ExerciseValue(new Id('deadlift', Exercise), 'Deadlift', 'hinge', 'barbell', 2.5),
      new ExerciseValue(new Id('sumo-deadlift', Exercise), 'Sumo Deadlift', 'hinge', 'barbell', 2.5),
      new ExerciseValue(new Id('romanian-deadlift', Exercise), 'Romanian Deadlift', 'hinge', 'barbell', 2.5),
      new ExerciseValue(new Id('trap-bar-deadlift', Exercise), 'Trap Bar Deadlift', 'hinge', 'barbell', 2.5),
      new ExerciseValue(new Id('good-morning', Exercise), 'Good Morning', 'hinge', 'barbell', 2.5),
      new ExerciseValue(new Id('hip-thrust', Exercise), 'Hip Thrust', 'hinge', 'barbell', 2.5),
      new ExerciseValue(new Id('back-extension', Exercise), 'Back Extension', 'hinge', 'bodyweight', 2.5),
      new ExerciseValue(new Id('kettlebell-swing', Exercise), 'Kettlebell Swing', 'hinge', 'kettlebell', 4.0),
      new ExerciseValue(new Id('bench-press', Exercise), 'Bench Press', 'press', 'barbell', 2.5),
      new ExerciseValue(new Id('incline-bench-press', Exercise), 'Incline Bench Press', 'press', 'barbell', 2.5),
      new ExerciseValue(new Id('close-grip-bench-press', Exercise), 'Close Grip Bench Press', 'press', 'barbell', 2.5),
      new ExerciseValue(new Id('overhead-press', Exercise), 'Overhead Press', 'press', 'barbell', 2.5),
      new ExerciseValue(new Id('push-press', Exercise), 'Push Press', 'press', 'barbell', 2.5),
      new ExerciseValue(new Id('dumbbell-bench-press', Exercise), 'Dumbbell Bench Press', 'press', 'dumbbell', 2.0),
      new ExerciseValue(new Id('incline-dumbbell-press', Exercise), 'Incline Dumbbell Press', 'press', 'dumbbell', 2.0),
      new ExerciseValue(new Id('dumbbell-shoulder-press', Exercise), 'Dumbbell Shoulder Press', 'press', 'dumbbell', 2.0),
      new ExerciseValue(new Id('machine-chest-press', Exercise), 'Machine Chest Press', 'press', 'machine', 5.0),
      new ExerciseValue(new Id('machine-shoulder-press', Exercise), 'Machine Shoulder Press', 'press', 'machine', 5.0),
      new ExerciseValue(new Id('dip', Exercise), 'Dip', 'press', 'bodyweight', 2.5),
      new ExerciseValue(new Id('push-up', Exercise), 'Push Up', 'press', 'bodyweight', 2.5),
      new ExerciseValue(new Id('pull-up', Exercise), 'Pull Up', 'pull', 'bodyweight', 2.5),
      new ExerciseValue(new Id('chin-up', Exercise), 'Chin Up', 'pull', 'bodyweight', 2.5),
      new ExerciseValue(new Id('muscle-up', Exercise), 'Muscle Up', 'pull', 'bodyweight', 2.5),
      new ExerciseValue(new Id('lat-pulldown', Exercise), 'Lat Pulldown', 'pull', 'cable', 2.5),
      new ExerciseValue(new Id('barbell-row', Exercise), 'Barbell Row', 'pull', 'barbell', 2.5),
      new ExerciseValue(new Id('dumbbell-row', Exercise), 'Dumbbell Row', 'pull', 'dumbbell', 2.0),
      new ExerciseValue(new Id('chest-supported-row', Exercise), 'Chest Supported Row', 'pull', 'machine', 5.0),
      new ExerciseValue(new Id('seated-cable-row', Exercise), 'Seated Cable Row', 'pull', 'cable', 2.5),
      new ExerciseValue(new Id('face-pull', Exercise), 'Face Pull', 'pull', 'cable', 2.5),
      new ExerciseValue(new Id('barbell-shrug', Exercise), 'Barbell Shrug', 'pull', 'barbell', 2.5),
      new ExerciseValue(new Id('inverted-row', Exercise), 'Inverted Row', 'pull', 'bodyweight', 2.5),
      new ExerciseValue(new Id('farmers-carry', Exercise), 'Farmers Carry', 'carry', 'dumbbell', 2.0),
      new ExerciseValue(new Id('suitcase-carry', Exercise), 'Suitcase Carry', 'carry', 'dumbbell', 2.0),
      new ExerciseValue(new Id('overhead-carry', Exercise), 'Overhead Carry', 'carry', 'dumbbell', 2.0),
      new ExerciseValue(new Id('plank', Exercise), 'Plank', 'core', 'bodyweight', 2.5),
      new ExerciseValue(new Id('hanging-leg-raise', Exercise), 'Hanging Leg Raise', 'core', 'bodyweight', 2.5),
      new ExerciseValue(new Id('ab-wheel-rollout', Exercise), 'Ab Wheel Rollout', 'core', 'bodyweight', 2.5),
      new ExerciseValue(new Id('cable-crunch', Exercise), 'Cable Crunch', 'core', 'cable', 2.5),
      new ExerciseValue(new Id('pallof-press', Exercise), 'Pallof Press', 'core', 'cable', 2.5),
      new ExerciseValue(new Id('weighted-sit-up', Exercise), 'Weighted Sit Up', 'core', 'bodyweight', 2.5),
      new ExerciseValue(new Id('barbell-curl', Exercise), 'Barbell Curl', 'isolation', 'barbell', 2.5),
      new ExerciseValue(new Id('dumbbell-curl', Exercise), 'Dumbbell Curl', 'isolation', 'dumbbell', 2.0),
      new ExerciseValue(new Id('hammer-curl', Exercise), 'Hammer Curl', 'isolation', 'dumbbell', 2.0),
      new ExerciseValue(new Id('triceps-pushdown', Exercise), 'Triceps Pushdown', 'isolation', 'cable', 2.5),
      new ExerciseValue(new Id('skull-crusher', Exercise), 'Skull Crusher', 'isolation', 'barbell', 2.5),
      new ExerciseValue(new Id('overhead-triceps-extension', Exercise), 'Overhead Triceps Extension', 'isolation', 'dumbbell', 2.0),
      new ExerciseValue(new Id('lateral-raise', Exercise), 'Lateral Raise', 'isolation', 'dumbbell', 2.0),
      new ExerciseValue(new Id('rear-delt-fly', Exercise), 'Rear Delt Fly', 'isolation', 'dumbbell', 2.0),
      new ExerciseValue(new Id('dumbbell-fly', Exercise), 'Dumbbell Fly', 'isolation', 'dumbbell', 2.0),
      new ExerciseValue(new Id('cable-fly', Exercise), 'Cable Fly', 'isolation', 'cable', 2.5),
      new ExerciseValue(new Id('leg-extension', Exercise), 'Leg Extension', 'isolation', 'machine', 5.0),
      new ExerciseValue(new Id('lying-leg-curl', Exercise), 'Lying Leg Curl', 'isolation', 'machine', 5.0),
      new ExerciseValue(new Id('standing-calf-raise', Exercise), 'Standing Calf Raise', 'isolation', 'machine', 5.0),
      new ExerciseValue(new Id('seated-calf-raise', Exercise), 'Seated Calf Raise', 'isolation', 'machine', 5.0),
      new ExerciseValue(new Id('wrist-curl', Exercise), 'Wrist Curl', 'isolation', 'barbell', 2.5),
      new ExerciseValue(new Id('hip-abduction', Exercise), 'Hip Abduction', 'isolation', 'machine', 5.0),
    ]);
    return seeds;
  },
});
