export default {
  id: 'learn-watercolor',
  title: 'Learn watercolor',
  audience: 'life',
  estimate: '~2 months',
  source: null,
  kinds: [
    { id: 'technique', hue: 'sky', label: 'Technique', description: 'Exercises that train one skill at a time' },
    { id: 'studies', hue: 'terracotta', label: 'Studies', description: 'Small real paintings that put the skills together' },
  ],
  nodes: [
    {
      id: 'swatch-chart',
      label: 'Swatch every paint you own',
      color: 'sky',
      prerequisites: [],
      description: 'With whatever brush and paper you have, paint a small labelled square of every color you own. Done is one chart you can pin up and refer to.',
    },
    {
      id: 'flat-wash',
      label: 'Lay a flat wash',
      color: 'sky',
      prerequisites: ['swatch-chart'],
      description: 'Fill a rectangle with one color in steady side-to-side strokes, keeping a wet bead moving down the paper. Done when a dry wash comes out one even tone, no stripes or blooms.',
    },
    {
      id: 'mixing-chart',
      label: 'Chart your two-color mixes',
      color: 'sky',
      prerequisites: ['swatch-chart'],
      description: 'Mix each pair of your colors in a grid and paint the result. Done is a chart that shows which pairs make the greens, greys, and darks you\'ll reach for.',
    },
    {
      id: 'graded-wash',
      label: 'Pull a graded wash',
      color: 'sky',
      prerequisites: ['flat-wash'],
      description: 'Start dark at the top and add water with each stroke so the color fades smoothly to almost nothing. Done when the fade reads as one motion with no hard bands.',
    },
    {
      id: 'wet-in-wet',
      label: 'Let two colors meet wet-in-wet',
      color: 'sky',
      prerequisites: ['flat-wash'],
      description: 'Wet the paper, drop in one color, then another, and let them bloom into each other. Done when you can roughly steer where the colors wander by how wet the paper is.',
    },
    {
      id: 'saved-whites',
      label: 'Save your whites on purpose',
      color: 'sky',
      prerequisites: ['flat-wash'],
      description: 'Sketch a few simple shapes and wash around them, leaving the bare paper as your brightest white. Done when the saved shapes have clean deliberate edges, not accidents.',
    },
    {
      id: 'hard-soft-edges',
      label: 'Practice hard and soft edges',
      color: 'sky',
      prerequisites: ['wet-in-wet'],
      description: 'On one sheet, paint shapes with crisp edges on dry paper, then soften one side of each with a clean damp brush. Done when you can choose which edge you\'ll get before the brush lands.',
    },
    {
      id: 'glazing',
      label: 'Glaze three transparent layers',
      color: 'sky',
      prerequisites: ['flat-wash', 'mixing-chart'],
      description: 'Paint a pale wash, let it dry completely, then lay two more over it so the color quietly deepens. Done when you can still see all three layers through each other.',
    },
    {
      id: 'value-study',
      label: 'Paint a three-value study',
      color: 'terracotta',
      prerequisites: ['graded-wash'],
      description: 'Pick one color and a plain object — a mug works — and paint it in only light, middle, and dark. Done when the object reads as solid from across the room.',
    },
    {
      id: 'sky-study',
      label: 'Paint a graded sky',
      color: 'terracotta',
      prerequisites: ['graded-wash', 'wet-in-wet'],
      description: 'Paint a sky that fades from deep at the top to pale at the horizon, dropping in soft clouds while it\'s still wet. Done when it dries looking like air, not like paint.',
    },
    {
      id: 'leaf-study',
      label: 'Paint one leaf from life',
      color: 'terracotta',
      prerequisites: ['hard-soft-edges', 'mixing-chart'],
      description: 'Put a real leaf in front of you, mix its green from your chart, and paint it with hard edges where it curls and soft edges where it turns away. Done when it\'s recognizably that leaf.',
    },
    {
      id: 'white-cup-study',
      label: 'Paint a white cup and its shadow',
      color: 'terracotta',
      prerequisites: ['saved-whites', 'glazing', 'value-study'],
      description: 'Paint a white cup by saving the paper for its lit side and glazing the shadow in slow layers. Done when the cup looks white even though you never used white paint.',
    },
    {
      id: 'postcard-landscape',
      label: 'Paint a postcard landscape',
      color: 'terracotta',
      prerequisites: ['sky-study', 'leaf-study'],
      description: 'Paint a small landscape in one sitting — a graded sky, a far tree line, one detailed thing up front. Done when it\'s signed and drying, whatever you think of it.',
    },
  ],
};
