export default {
  id: 'rust-from-zero',
  title: 'Rust from zero',
  audience: 'dev',
  estimate: '~3 months',
  source: 'roadmap.sh (CC BY-SA)',
  kinds: [
    { id: 'core', hue: 'brick', label: 'Core', description: 'The language itself, one concept at a time' },
    { id: 'practice', hue: 'olive', label: 'Practice', description: 'Programs you write to make the concepts stick' },
    { id: 'ship', hue: 'gold', label: 'Ship', description: 'Work you release for other people to use' },
  ],
  nodes: [
    {
      id: 'install-rust',
      label: 'Install Rust and run hello, cargo',
      color: 'brick',
      prerequisites: [],
      description: 'Install rustup, create a project with cargo new, and run it. Done when cargo run prints your greeting and you know where the code lives.',
      links: ['https://www.rust-lang.org/learn/get-started'],
    },
    {
      id: 'basic-syntax',
      label: 'Learn variables, types, and flow',
      color: 'brick',
      prerequisites: ['install-rust'],
      description: 'Variables and mutability, scalar and compound types, functions, if, and loops — chapter 3 of the Book. Done when you can write fizzbuzz without looking anything up.',
      links: ['https://doc.rust-lang.org/book/'],
    },
    {
      id: 'guessing-game',
      label: 'Build the guessing game',
      color: 'olive',
      prerequisites: ['install-rust'],
      description: 'Follow the Book\'s guided project: read input, parse numbers, and loop until the guess lands. Done when it compiles, runs, and you can say what match is doing.',
      links: ['https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html'],
    },
    {
      id: 'ownership',
      label: 'Understand ownership and borrowing',
      color: 'brick',
      prerequisites: ['basic-syntax'],
      description: 'Moves, borrows, mutable references, and slices — the rules everything else in Rust stands on. Done when you can predict what the borrow checker will say before it says it.',
      links: ['https://doc.rust-lang.org/book/ch04-00-understanding-ownership.html'],
    },
    {
      id: 'structs-and-enums',
      label: 'Model data with structs and enums',
      color: 'brick',
      prerequisites: ['ownership'],
      description: 'Define your own types, add methods with impl, and take values apart with match. Done when Option feels like a friend instead of a speed bump.',
    },
    {
      id: 'collections-and-strings',
      label: 'Use vectors, strings, and hash maps',
      color: 'brick',
      prerequisites: ['ownership'],
      description: 'The workhorse collections, and why String and &str are different things. Done when you can build a word counter without fighting the compiler.',
    },
    {
      id: 'error-handling',
      label: 'Handle errors with Result',
      color: 'brick',
      prerequisites: ['structs-and-enums'],
      description: 'Panicking versus returning Result, propagating with the question mark operator, and designing functions that can fail honestly. Done when your code has no unwrap you cannot defend.',
    },
    {
      id: 'rustlings',
      label: 'Work through rustlings',
      color: 'olive',
      prerequisites: ['basic-syntax'],
      description: 'Small exercises that drill each concept as you meet it in the Book. Done when the ownership and error-handling sets pass without hints.',
      links: ['https://github.com/rust-lang/rustlings'],
    },
    {
      id: 'modules-and-cargo',
      label: 'Organize code with modules',
      color: 'brick',
      prerequisites: ['basic-syntax'],
      description: 'Split a growing program into modules, understand use paths, and lean on cargo and crates.io. Done when your project has more than one file and no giant main.rs.',
    },
    {
      id: 'cli-tool',
      label: 'Build a grep-style CLI tool',
      color: 'olive',
      prerequisites: ['collections-and-strings', 'error-handling', 'modules-and-cargo'],
      description: 'The Book\'s minigrep: arguments, file reading, search, and real error messages, split across lib.rs and main.rs. Done when it finds text in a file and fails politely when the file is missing.',
      links: ['https://doc.rust-lang.org/book/ch12-00-an-io-project.html'],
    },
    {
      id: 'traits-and-generics',
      label: 'Abstract with traits and generics',
      color: 'brick',
      prerequisites: ['structs-and-enums'],
      description: 'Write functions and types that work over many types, and define shared behavior with traits. Done when you can explain what impl Trait means in a signature.',
    },
    {
      id: 'lifetimes',
      label: 'Read and write lifetimes',
      color: 'brick',
      prerequisites: ['traits-and-generics'],
      description: 'Why references need lifetimes, the elision rules, and the annotations that make borrowed data safe to return. Done when a lifetime error reads like information, not punishment.',
    },
    {
      id: 'testing',
      label: 'Write tests with cargo test',
      color: 'olive',
      prerequisites: ['modules-and-cargo'],
      description: 'Unit tests next to the code, integration tests in the tests directory, and the assert macros. Done when a red test has saved you at least once.',
    },
    {
      id: 'iterators-and-closures',
      label: 'Think in iterators and closures',
      color: 'brick',
      prerequisites: ['traits-and-generics'],
      description: 'Closures that capture their environment, and iterator chains that replace index loops. Done when map, filter, and collect are your first instinct.',
    },
    {
      id: 'refactor-cli',
      label: 'Refactor your CLI with iterators',
      color: 'olive',
      prerequisites: ['cli-tool', 'iterators-and-closures', 'testing'],
      description: 'Rework minigrep the way the Book does: replace clone-heavy loops with iterator chains. Done when the code got shorter and the tests still pass.',
    },
    {
      id: 'smart-pointers',
      label: 'Reach for Box, Rc, and RefCell',
      color: 'brick',
      prerequisites: ['lifetimes'],
      description: 'Heap allocation, shared ownership, and interior mutability — and the cost each one buys. Done when you know which pointer a linked structure needs and why.',
    },
    {
      id: 'concurrency',
      label: 'Share work across threads',
      color: 'brick',
      prerequisites: ['smart-pointers'],
      description: 'Spawn threads, pass messages over channels, and share state with Arc and Mutex. Done when you can explain how Send and Sync make data races a compile error.',
    },
    {
      id: 'web-server',
      label: 'Build a multithreaded web server',
      color: 'olive',
      prerequisites: ['concurrency'],
      description: 'The Book\'s final project: a thread pool serving real HTTP requests from scratch. Done when your browser gets a page from code you wrote top to bottom.',
      links: ['https://doc.rust-lang.org/book/ch21-00-final-project-a-web-server.html'],
    },
    {
      id: 'publish-crate',
      label: 'Publish a crate to crates.io',
      color: 'gold',
      prerequisites: ['refactor-cli'],
      description: 'Extract your search logic into a library crate, document it, and publish. Choose the name carefully — crates.io names are permanent, and a published version can never be replaced. Done when cargo add finds your crate from any machine.',
    },
    {
      id: 'contribute',
      label: 'Send a PR to a Rust project',
      color: 'gold',
      prerequisites: ['refactor-cli'],
      description: 'Pick a crate you use, find a good first issue, and send the fix as a pull request. Done when it is submitted and you have answered the review in someone else\'s codebase — the merge is the maintainer\'s call, not yours.',
    },
    {
      id: 'ship-project',
      label: 'Put a Rust project in real hands',
      color: 'gold',
      prerequisites: ['web-server', 'publish-crate'],
      description: 'Release something real: a hosted service or a CLI with binaries on GitHub Releases. Done when a stranger runs your code without your help.',
    },
  ],
};
