export default {
  id: 'ship-v1',
  title: 'Ship v1',
  audience: 'dev',
  estimate: '~6 weeks',
  source: null,
  kinds: [
    { id: 'build', hue: 'terracotta', label: 'Build', description: 'Scoping and building the product itself' },
    { id: 'polish', hue: 'sky', label: 'Polish', description: 'The pass that makes it feel finished' },
    { id: 'launch', hue: 'gold', label: 'Launch', description: 'Getting it in front of real people' },
  ],
  nodes: [
    {
      id: 'write-the-promise',
      label: 'Write the one-sentence promise',
      color: 'terracotta',
      prerequisites: [],
      description: 'Name who this is for and what it does for them, in one sentence you could say out loud without flinching. Done when a stranger hears it and knows whether they would want it.',
    },
    {
      id: 'cut-the-scope',
      label: 'Cut scope to one core flow',
      color: 'terracotta',
      prerequisites: ['write-the-promise'],
      description: 'List everything v1 could be, then cut until a single flow delivers the promise. Done when the spec fits on one page and the cuts are written down too.',
    },
    {
      id: 'pick-a-boring-stack',
      label: 'Pick a boring stack and deploy it',
      color: 'terracotta',
      prerequisites: ['write-the-promise'],
      description: 'Choose tools you already know, wire up the repository, and deploy a hello-world skeleton to production on day one. Done when a URL serves your empty app.',
    },
    {
      id: 'sketch-the-flow',
      label: 'Sketch the core flow on paper',
      color: 'terracotta',
      prerequisites: ['cut-the-scope'],
      description: 'Wireframe every screen of the one flow, from arrival to the moment of value. Done when you can walk someone through the paper version and they never get lost.',
    },
    {
      id: 'walking-skeleton',
      label: 'Build the walking skeleton',
      color: 'terracotta',
      prerequisites: ['pick-a-boring-stack', 'sketch-the-flow'],
      description: 'The thinnest end-to-end slice of the real flow, deployed: real navigation, real screens, hard-coded edges. Done when you can click from start to value, even if the value is fake.',
    },
    {
      id: 'core-feature',
      label: 'Make the core feature real',
      color: 'terracotta',
      prerequisites: ['walking-skeleton'],
      description: 'Replace the fake middle with the real thing the promise depends on. Done when the product does the job for real data, start to finish.',
    },
    {
      id: 'dogfood',
      label: 'Dogfood it for a week',
      color: 'sky',
      prerequisites: ['core-feature'],
      description: 'Use your product for its real purpose every day and keep a list of what made you wince. Done after seven honest days and a prioritized fix list.',
    },
    {
      id: 'onboarding-pass',
      label: 'Smooth the first-run experience',
      color: 'sky',
      prerequisites: ['dogfood'],
      description: 'Empty states, sign-up friction, and the path to first value for someone with zero context. Done when a friend reaches the payoff without you saying a word.',
    },
    {
      id: 'failure-pass',
      label: 'Handle failure gracefully',
      color: 'sky',
      prerequisites: ['dogfood'],
      description: 'Bad input, slow networks, and broken sessions — decide what each failure looks like on purpose. Done when nothing dead-ends without an explanation and a way back.',
    },
    {
      id: 'landing-page',
      label: 'Make the landing page',
      color: 'gold',
      prerequisites: ['core-feature'],
      description: 'One page: the promise, a real screenshot, and one obvious call to action. Done when it loads fast and someone can sign up from their phone.',
    },
    {
      id: 'instrument',
      label: 'Wire up analytics and feedback',
      color: 'sky',
      prerequisites: ['core-feature'],
      description: 'Track the handful of events that trace your core flow, and give users one obvious way to reach you. Done when you can see the funnel and hear the complaints.',
    },
    {
      id: 'friendly-beta',
      label: 'Run a friendly beta',
      color: 'gold',
      prerequisites: ['onboarding-pass', 'failure-pass'],
      description: 'Put it in the hands of five people who fit the promise and watch them use it. Done when the top three stumbles are found and fixed.',
    },
    {
      id: 'launch-day',
      label: 'Launch it where your people are',
      color: 'gold',
      prerequisites: ['friendly-beta', 'landing-page', 'instrument'],
      description: 'Post to the communities your promise serves — Show HN, Product Hunt, a subreddit — and answer everyone all day. Done when the posts are up and every comment has an answer before you go to bed.',
    },
    {
      id: 'first-fix-release',
      label: 'Ship the first fix release',
      color: 'gold',
      prerequisites: ['launch-day'],
      description: 'Sort the launch feedback, fix the sharpest edges, and ship within the week — v1 is a conversation, not a monument. Done when changes born from real users are live.',
    },
  ],
};
