# engine.md §9.1: the edge forwards every Authorization and Cookie line as received, and every Set-Cookie line back.
# Run: cmake -DCADDYFILE=<path> -P caddyfile_forwards_credentials.cmake. It fails when a line of the Caddyfile, outside
# a comment, names one of those fields (as `Cookie`, `-Cookie`, `+Cookie` or `>Cookie`), or rewrites fields by a
# pattern that could reach them.
if(NOT EXISTS "${CADDYFILE}")
  message(FATAL_ERROR "No Caddyfile at ${CADDYFILE}")
endif()
file(STRINGS "${CADDYFILE}" lines)
set(proxies 0)
set(offending "")
foreach(line IN LISTS lines)
  string(REGEX REPLACE "#.*$" "" code "${line}")
  string(TOLOWER "${code}" code)
  if(code MATCHES "^[ \t]*reverse_proxy[ \t]")
    math(EXPR proxies "${proxies} + 1")
  endif()
  string(REGEX MATCHALL "[^ \t\"]+" words "${code}")
  set(touches FALSE)
  foreach(word IN LISTS words)
    string(REGEX REPLACE "^[-+>]" "" field "${word}")
    if(field MATCHES "^(authorization|cookie|set-cookie)$")
      set(touches TRUE)
    endif()
  endforeach()
  if(code MATCHES "^[ \t]*(header_up|header_down|request_header|header)[ \t]+[^ \t]*\\*")
    set(touches TRUE)
  endif()
  if(touches)
    string(APPEND offending "\n  ${line}")
  endif()
endforeach()
if(proxies EQUAL 0)
  message(FATAL_ERROR "${CADDYFILE} proxies nothing: the check would pass vacuously")
endif()
if(offending)
  message(FATAL_ERROR "${CADDYFILE} touches a credential field on its way through the edge:${offending}")
endif()
message(STATUS "${CADDYFILE}: ${proxies} reverse_proxy blocks, none touching Authorization, Cookie or Set-Cookie")
