// Generated by tools/schema_gen.py from packages/api-contract/sync/composition.json. Do not edit.
package works.windmill.sync.schema

import works.windmill.sync.core.Registry

object SyncSchema {
    val registry = Registry.compose("windmill", listOf(Gym.registry, Journal.registry))
    val version = registry.version
}
