import DomainKit
import SyncCore

public enum SeedExercises {
  public static let all: [Exercise] = [
    Exercise(id: ID("back-squat"), name: "Back Squat", pattern: "squat", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("front-squat"), name: "Front Squat", pattern: "squat", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("goblet-squat"), name: "Goblet Squat", pattern: "squat", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("bulgarian-split-squat"), name: "Bulgarian Split Squat", pattern: "squat", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("walking-lunge"), name: "Walking Lunge", pattern: "squat", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("step-up"), name: "Step Up", pattern: "squat", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("leg-press"), name: "Leg Press", pattern: "squat", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("hack-squat"), name: "Hack Squat", pattern: "squat", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("deadlift"), name: "Deadlift", pattern: "hinge", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("sumo-deadlift"), name: "Sumo Deadlift", pattern: "hinge", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("romanian-deadlift"), name: "Romanian Deadlift", pattern: "hinge", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("trap-bar-deadlift"), name: "Trap Bar Deadlift", pattern: "hinge", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("good-morning"), name: "Good Morning", pattern: "hinge", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("hip-thrust"), name: "Hip Thrust", pattern: "hinge", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("back-extension"), name: "Back Extension", pattern: "hinge", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("kettlebell-swing"), name: "Kettlebell Swing", pattern: "hinge", equipment: "kettlebell", stepKg: 4.0),
    Exercise(id: ID("bench-press"), name: "Bench Press", pattern: "press", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("incline-bench-press"), name: "Incline Bench Press", pattern: "press", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("close-grip-bench-press"), name: "Close Grip Bench Press", pattern: "press", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("overhead-press"), name: "Overhead Press", pattern: "press", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("push-press"), name: "Push Press", pattern: "press", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("dumbbell-bench-press"), name: "Dumbbell Bench Press", pattern: "press", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("incline-dumbbell-press"), name: "Incline Dumbbell Press", pattern: "press", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("dumbbell-shoulder-press"), name: "Dumbbell Shoulder Press", pattern: "press", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("machine-chest-press"), name: "Machine Chest Press", pattern: "press", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("machine-shoulder-press"), name: "Machine Shoulder Press", pattern: "press", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("dip"), name: "Dip", pattern: "press", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("push-up"), name: "Push Up", pattern: "press", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("pull-up"), name: "Pull Up", pattern: "pull", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("chin-up"), name: "Chin Up", pattern: "pull", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("muscle-up"), name: "Muscle Up", pattern: "pull", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("lat-pulldown"), name: "Lat Pulldown", pattern: "pull", equipment: "cable", stepKg: 2.5),
    Exercise(id: ID("barbell-row"), name: "Barbell Row", pattern: "pull", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("dumbbell-row"), name: "Dumbbell Row", pattern: "pull", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("chest-supported-row"), name: "Chest Supported Row", pattern: "pull", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("seated-cable-row"), name: "Seated Cable Row", pattern: "pull", equipment: "cable", stepKg: 2.5),
    Exercise(id: ID("face-pull"), name: "Face Pull", pattern: "pull", equipment: "cable", stepKg: 2.5),
    Exercise(id: ID("barbell-shrug"), name: "Barbell Shrug", pattern: "pull", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("inverted-row"), name: "Inverted Row", pattern: "pull", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("farmers-carry"), name: "Farmers Carry", pattern: "carry", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("suitcase-carry"), name: "Suitcase Carry", pattern: "carry", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("overhead-carry"), name: "Overhead Carry", pattern: "carry", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("plank"), name: "Plank", pattern: "core", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("hanging-leg-raise"), name: "Hanging Leg Raise", pattern: "core", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("ab-wheel-rollout"), name: "Ab Wheel Rollout", pattern: "core", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("cable-crunch"), name: "Cable Crunch", pattern: "core", equipment: "cable", stepKg: 2.5),
    Exercise(id: ID("pallof-press"), name: "Pallof Press", pattern: "core", equipment: "cable", stepKg: 2.5),
    Exercise(id: ID("weighted-sit-up"), name: "Weighted Sit Up", pattern: "core", equipment: "bodyweight", stepKg: 2.5),
    Exercise(id: ID("barbell-curl"), name: "Barbell Curl", pattern: "isolation", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("dumbbell-curl"), name: "Dumbbell Curl", pattern: "isolation", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("hammer-curl"), name: "Hammer Curl", pattern: "isolation", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("triceps-pushdown"), name: "Triceps Pushdown", pattern: "isolation", equipment: "cable", stepKg: 2.5),
    Exercise(id: ID("skull-crusher"), name: "Skull Crusher", pattern: "isolation", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("overhead-triceps-extension"), name: "Overhead Triceps Extension", pattern: "isolation", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("lateral-raise"), name: "Lateral Raise", pattern: "isolation", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("rear-delt-fly"), name: "Rear Delt Fly", pattern: "isolation", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("dumbbell-fly"), name: "Dumbbell Fly", pattern: "isolation", equipment: "dumbbell", stepKg: 2.0),
    Exercise(id: ID("cable-fly"), name: "Cable Fly", pattern: "isolation", equipment: "cable", stepKg: 2.5),
    Exercise(id: ID("leg-extension"), name: "Leg Extension", pattern: "isolation", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("lying-leg-curl"), name: "Lying Leg Curl", pattern: "isolation", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("standing-calf-raise"), name: "Standing Calf Raise", pattern: "isolation", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("seated-calf-raise"), name: "Seated Calf Raise", pattern: "isolation", equipment: "machine", stepKg: 5.0),
    Exercise(id: ID("wrist-curl"), name: "Wrist Curl", pattern: "isolation", equipment: "barbell", stepKg: 2.5),
    Exercise(id: ID("hip-abduction"), name: "Hip Abduction", pattern: "isolation", equipment: "machine", stepKg: 5.0),
  ]
}
