import SyncCore

// The SyncSchema target's sources, from the product registries: per registry, `<Product>.generated.swift` holding the
// registry as a literal of SyncCore's JSON and its type and command names; and `SyncSchema.swift`, composing them into
// the one registry the app runs. Pure: main.swift reads the registry files and writes or checks what this answers.

struct RegistryFile {
  let name: String
  let json: JSON
}

struct GeneratedFile: Equatable {
  let name: String
  let text: String
}

struct GenerationError: Error, CustomStringConvertible {
  let description: String
}

enum SchemaSources {
  static let directory = "packages/api-contract/sync"
  static let composedName = "windmill"
  // Enum names a registry cannot take: they would shadow a name SyncSchema uses or Swift reserves.
  static let reservedEnumNames: Set<String> = ["SyncSchema", "SyncCore", "Registry", "Any", "Self", "Type", "Protocol"]

  // A registry, decoded, and the enum its sources declare.
  struct Part {
    let file: String
    let enumName: String
    let registry: Registry
  }

  // Every file of the target, sorted by name. A registry must decode, and decode losslessly, so the literal written is
  // the file itself; the registries must compose, so SyncSchema.swift cannot fail when the app first reads it.
  static func files(from registries: [RegistryFile]) throws -> [GeneratedFile] {
    let parts = try registries.sorted { $0.name < $1.name }.map(part)
    guard !parts.isEmpty else { throw GenerationError(description: "no product registry in \(directory)") }
    do {
      _ = try Registry(name: composedName, composing: parts.map(\.registry))
    } catch {
      throw GenerationError(description: "the product registries do not compose: \(error)")
    }
    for (index, part) in parts.enumerated() where parts[..<index].contains(where: { $0.enumName == part.enumName }) {
      throw GenerationError(description: "\(part.file) declares a second enum \(part.enumName)")
    }
    return (try parts.map(productFile) + [schemaFile(parts)]).sorted { $0.name < $1.name }
  }

  static func part(_ file: RegistryFile) throws -> Part {
    let registry: Registry
    do {
      registry = try Registry(json: file.json)
    } catch {
      throw GenerationError(description: "\(file.name): \(error)")
    }
    var written = try file.json.asObject()
    written["$schema"] = nil
    guard registry.json == .object(written) else {
      throw GenerationError(
        description: "\(file.name) does not round-trip through the registry decoder: it states a key the decoder drops, "
          + "such as a default value")
    }
    let enumName = registry.name.split(separator: "-").map { $0.prefix(1).uppercased() + String($0.dropFirst()) }.joined()
    guard !reservedEnumNames.contains(enumName) else {
      throw GenerationError(description: "\(file.name): the registry \(registry.name) would declare the reserved enum \(enumName)")
    }
    return Part(file: file.name, enumName: enumName, registry: registry)
  }

  static func productFile(_ part: Part) throws -> GeneratedFile {
    var commands: [(member: String, name: String)] = []
    for command in part.registry.commands {
      let member = String(command.name.drop { $0 != "." }.dropFirst())
      guard !commands.contains(where: { $0.member == member }) else {
        throw GenerationError(description: "\(part.file): two commands are named \(member)")
      }
      commands.append((member, command.name))
    }
    var text = """
      // Generated by SyncSchemaGen from \(directory)/\(part.file). Do not edit.

      import SyncCore

      public enum \(part.enumName) {
        public enum Types {

      """
    for type in part.registry.types {
      text += "    public static let \(SwiftLiteral.identifier(type.name)) = \(SwiftLiteral.string(type.name))\n"
    }
    text += "  }\n"
    if !commands.isEmpty {
      text += "\n  public enum Commands {\n"
      for command in commands {
        text += "    public static let \(SwiftLiteral.identifier(command.member)) = \(SwiftLiteral.string(command.name))\n"
      }
      text += "  }\n"
    }
    let lead = "  static let registryFile: JSON = "
    text += "\n\(lead)\(SwiftLiteral.render(part.registry.json, indent: 2, column: lead.count))\n}\n"
    return GeneratedFile(name: "\(part.enumName).generated.swift", text: text)
  }

  static func schemaFile(_ parts: [Part]) -> GeneratedFile {
    let decoded = parts.map { "    Registry(json: \($0.enumName).registryFile),\n" }.joined()
    return GeneratedFile(name: "SyncSchema.swift", text: """
      // Generated by SyncSchemaGen from the product registries in \(directory). Do not edit.

      import SyncCore

      public enum SyncSchema {
        public static let registry = try! Registry(name: \(SwiftLiteral.string(composedName)), composing: [
      \(decoded)  ])
        public static let version = registry.version
      }

      """)
  }

  // The names of the target's files that differ from what the registries generate, byte for byte: changed, missing, or
  // left over from a registry that is gone. Empty when the checked-in target is current.
  static func stale(_ generated: [GeneratedFile], existing: [String: [UInt8]]) -> [String] {
    let changed = generated.filter { existing[$0.name] != Array($0.text.utf8) }.map(\.name)
    let extra = existing.keys.filter { name in !generated.contains { $0.name == name } }
    return (changed + extra).sorted()
  }
}

// A JSON value as a Swift literal of SyncCore's JSON, and the names and strings the sources declare.
enum SwiftLiteral {
  static let width = 120
  static let keywords: Set<String> = [
    "associatedtype", "class", "deinit", "enum", "extension", "fileprivate", "func", "import", "init", "inout", "internal",
    "let", "operator", "private", "precedencegroup", "protocol", "public", "rethrows", "static", "struct", "subscript",
    "typealias", "var", "break", "case", "catch", "continue", "default", "defer", "do", "else", "fallthrough", "for",
    "guard", "if", "in", "repeat", "return", "throw", "switch", "where", "while", "as", "await", "false", "is", "nil",
    "self", "super", "throws", "true", "try",
  ]

  // `json` starting at `column` of a line indented by `indent`: on that line when it fits the width with the comma after
  // it, otherwise one member per line.
  static func render(_ json: JSON, indent: Int, column: Int) -> String {
    let inline = self.inline(json)
    guard column + inline.count + 1 > width, let members = members(of: json) else { return inline }
    let pad = String(repeating: " ", count: indent + 2)
    let lines = members.map { member in
      let label = member.key.map { "\(string($0)): " } ?? ""
      return pad + label + render(member.value, indent: indent + 2, column: pad.count + label.count) + ","
    }
    return "[\n" + lines.joined(separator: "\n") + "\n" + String(repeating: " ", count: indent) + "]"
  }

  static func inline(_ json: JSON) -> String {
    switch json {
    case .null: return ".null"
    case .bool(let flag): return flag ? "true" : "false"
    case .number(let number): return self.number(number)
    case .string(let text): return string(text)
    case .array(let items): return "[" + items.map(inline).joined(separator: ", ") + "]"
    case .object(let object):
      guard !object.isEmpty else { return "[:]" }
      return "[" + object.members.map { "\(string($0.key)): \(inline($0.value))" }.joined(separator: ", ") + "]"
    }
  }

  // A non-empty array's items or object's members; nil for any other value, which never breaks across lines.
  static func members(of json: JSON) -> [(key: String?, value: JSON)]? {
    switch json {
    case .array(let items) where !items.isEmpty: items.map { (key: nil, value: $0) }
    case .object(let object) where !object.isEmpty: object.members.map { (key: $0.key, value: $0.value) }
    default: nil
    }
  }

  // The number's JCS text. A safe integer is an integer literal; any other number a float literal, which Swift rounds
  // correctly to the same double.
  static func number(_ number: JSON.Number) -> String {
    let text = number.description
    if number.value.rounded() == number.value && number.value.magnitude <= Double(JSON.maxSafeInteger) { return text }
    return text.contains { $0 == "." || $0 == "e" } ? text : text + ".0"
  }

  // A string literal holding exactly the text's scalars: printable ASCII as itself, every other scalar escaped.
  static func string(_ text: String) -> String {
    var literal = "\""
    for scalar in text.unicodeScalars {
      switch scalar {
      case "\"": literal += "\\\""
      case "\\": literal += "\\\\"
      case " "..."~": literal.unicodeScalars.append(scalar)
      default: literal += "\\u{\(String(scalar.value, radix: 16, uppercase: true))}"
      }
    }
    return literal + "\""
  }

  static func identifier(_ name: String) -> String {
    keywords.contains(name) ? "`\(name)`" : name
  }
}
