// Generated by SyncSchemaGen from packages/api-contract/sync/gym.registry.json. Do not edit.

import SyncCore

public enum Gym {
  public static let scope = ScopeRef.product("gym")

  public enum Types {
    public static let routine = "routine"
    public static let exercise = "exercise"
    public static let exerciseName = "exerciseName"
    public static let session = "session"
    public static let set = "set"
    public static let note = "note"
    public static let weighin = "weighin"
    public static let prefs = "prefs"
    public static let proposal = "proposal"
  }

  public enum Commands {
    public static let start = "gym.start"
    public static let importSession = "gym.importSession"
    public static let correctSession = "gym.correctSession"
    public static let finish = "gym.finish"
    public static let applyProposal = "gym.applyProposal"
    public static let dismissProposal = "gym.dismissProposal"
    public static let closeStale = "gym.closeStale"
  }

  public enum Codes {
    public static let payloadConflict: RefusalCode = "payload-conflict"
    public static let sessionFinished: RefusalCode = "session-finished"
    public static let sessionOpen: RefusalCode = "session-open"
    public static let sessionOverlap: RefusalCode = "session-overlap"
    public static let unknownExercise: RefusalCode = "unknown-exercise"
    public static let badInstant: RefusalCode = "bad-instant"
    public static let proposalSettled: RefusalCode = "proposal-settled"
    public static let proposalSuperseded: RefusalCode = "proposal-superseded"
  }

  public enum Defaults {
    public enum Routine {
      public static let position: Int = 0
    }

    public enum Prefs {
      public static let confirmHaptic: Bool = true
      public static let confirmSound: Bool = false
      public static let restSeconds: Int? = nil
      public static let restSound: Bool = true
      public static let units: String = "kg"
    }

    public enum Proposal {
      public static let state: String = "pending"
    }
  }

  static let registryFile: JSON = [
    "commands": [
      [
        "args": [
          "id": ["type": "ref<session>"],
          "joinOpenSession": ["domain": ["type": "boolean"], "type": "json"],
          "routineId": ["optional": true, "type": "ref<routine>"],
          "startedAt": ["type": "time"],
        ],
        "name": "gym.start",
        "origins": ["replica", "server"],
        "predicts": ["session"],
        "scope": "product:gym",
        "serverInternal": false,
      ],
      [
        "args": [
          "finishedAt": ["type": "instant"],
          "id": ["type": "ref<session>"],
          "routineId": ["optional": true, "type": "ref<routine>"],
          "sets": [
            "domain": [
              "items": [
                "properties": [
                  "completedAt": ["integer": true, "min": 0, "type": "number"],
                  "exerciseId": ["pattern": "^[A-Za-z0-9_-]{1,64}$", "type": "string"],
                  "id": ["pattern": "^[A-Za-z0-9_-]{8,64}$", "type": "string"],
                  "kind": ["enum": ["warmup", "working", "drop", "failure"], "type": "string"],
                  "note": ["max": 4000, "type": "string", "unit": "bytes"],
                  "reps": ["integer": true, "max": 500, "min": 1, "type": "number"],
                  "rpe": ["max": 10, "min": 1, "nullable": true, "quantum": 0.1, "type": "number"],
                  "weightKg": ["max": 500, "min": -500, "quantum": 0.01, "type": "number"],
                ],
                "required": ["id", "exerciseId", "weightKg", "reps", "completedAt"],
                "type": "object",
              ],
              "maxItems": 200,
              "type": "array",
            ],
            "type": "json",
          ],
          "startedAt": ["type": "instant"],
        ],
        "name": "gym.importSession",
        "origins": ["replica", "server"],
        "predicts": ["session", "set"],
        "scope": "product:gym",
        "serverInternal": false,
      ],
      [
        "args": [
          "finishedAt": ["type": "instant"],
          "requestId": ["domain": ["pattern": "^[A-Za-z0-9_-]{8,64}$", "type": "string"], "type": "json"],
          "routineName": ["domain": ["max": 240, "nullable": true, "type": "string", "unit": "bytes"], "type": "json"],
          "sessionId": ["type": "ref<session>"],
          "sets": [
            "domain": [
              "items": [
                "properties": [
                  "completedAt": ["integer": true, "min": 0, "type": "number"],
                  "exerciseId": ["pattern": "^[A-Za-z0-9_-]{1,64}$", "type": "string"],
                  "id": ["pattern": "^[A-Za-z0-9_-]{8,64}$", "type": "string"],
                  "note": ["max": 4000, "type": "string", "unit": "bytes"],
                  "reps": ["integer": true, "max": 500, "min": 1, "type": "number"],
                  "rpe": ["max": 10, "min": 1, "nullable": true, "quantum": 0.1, "type": "number"],
                  "setNumber": ["integer": true, "max": 2147483647, "min": 1, "type": "number"],
                  "weightKg": ["max": 500, "min": -500, "quantum": 0.01, "type": "number"],
                ],
                "required": ["id", "exerciseId", "setNumber", "weightKg", "reps", "completedAt"],
                "type": "object",
              ],
              "maxItems": 200,
              "type": "array",
            ],
            "type": "json",
          ],
          "startedAt": ["type": "instant"],
        ],
        "name": "gym.correctSession",
        "origins": ["replica", "server"],
        "predicts": ["session", "set"],
        "scope": "product:gym",
        "serverInternal": false,
      ],
      [
        "args": ["finishedAt": ["type": "time"], "sessionId": ["type": "ref<session>"]],
        "name": "gym.finish",
        "origins": ["replica", "server"],
        "predicts": ["session"],
        "scope": "product:gym",
        "serverInternal": false,
      ],
      [
        "args": ["proposalId": ["type": "ref<proposal>"]],
        "name": "gym.applyProposal",
        "origins": ["replica", "server"],
        "predicts": ["proposal", "routine"],
        "scope": "product:gym",
        "serverInternal": false,
      ],
      [
        "args": ["proposalId": ["type": "ref<proposal>"]],
        "name": "gym.dismissProposal",
        "origins": ["replica", "server"],
        "predicts": ["proposal"],
        "scope": "product:gym",
        "serverInternal": false,
      ],
      [
        "args": [:],
        "beforePull": true,
        "name": "gym.closeStale",
        "origins": ["server"],
        "scope": "product:gym",
        "serverInternal": true,
      ],
    ],
    "minVersion": 4,
    "products": [
      "gym": [
        "codes": [
          "payload-conflict",
          "session-finished",
          "session-open",
          "session-overlap",
          "unknown-exercise",
          "bad-instant",
          "proposal-settled",
          "proposal-superseded",
        ],
        "device": [
          "movement": [
            "keyPattern": "^movement:[A-Za-z0-9_-]{8,64}$",
            "value": ["pattern": "^[A-Za-z0-9_-]{1,64}$", "type": "string"],
          ],
          "movementOrder": [
            "keyPattern": "^movementOrder:[A-Za-z0-9_-]{8,64}$",
            "value": ["items": ["pattern": "^[A-Za-z0-9_-]{1,64}$", "type": "string"], "type": "array"],
          ],
          "offer": [
            "keyPattern": "^offer:[A-Za-z0-9_-]{8,64}$",
            "value": ["pattern": "^[A-Za-z0-9_-]{8,64}$", "type": "string"],
          ],
          "rack": ["keyPattern": "^rack:[A-Za-z0-9_-]{8,64}$", "value": ["type": "json"]],
        ],
        "surfaces": ["web", "ios", "android"],
      ],
    ],
    "registry": "gym",
    "types": [
      [
        "deadRows": "spent",
        "fields": [
          "createdDoor": ["domain": ["enum": ["mcp", "ask"], "type": "string"], "kind": "const", "writer": "server"],
          "entries": [
            "domain": [
              "items": [
                "properties": [
                  "exerciseId": ["pattern": "^[A-Za-z0-9_-]{1,64}$", "type": "string"],
                  "restSeconds": ["integer": true, "max": 900, "min": 15, "type": "number"],
                  "sets": [
                    "items": [
                      "properties": [
                        "reps": ["integer": true, "max": 100, "min": 1, "type": "number"],
                        "weightKg": ["max": 500, "min": -500, "quantum": 0.01, "type": "number"],
                      ],
                      "type": "object",
                    ],
                    "maxItems": 20,
                    "type": "array",
                  ],
                ],
                "required": ["exerciseId"],
                "type": "object",
              ],
              "maxItems": 50,
              "type": "array",
            ],
            "kind": "lww",
            "writer": "client",
          ],
          "name": [
            "domain": ["type": "string"],
            "kind": "lww",
            "max": 240,
            "min": 1,
            "unit": "bytes",
            "writer": "client",
          ],
          "position": [
            "default": 0,
            "domain": ["integer": true, "max": 2147483647, "min": 0, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
        ],
        "idPattern": "^[A-Za-z0-9_-]{8,64}$",
        "idSpace": "global",
        "identity": "minted",
        "life": true,
        "mint": [
          "alphabet": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
          "length": 16,
          "prefix": "",
        ],
        "origins": ["replica", "server"],
        "primary": true,
        "revivable": false,
        "scope": "product:gym",
        "seeded": ["ordinalMax": 99999, "seedMax": 58],
        "type": "routine",
      ],
      [
        "deadRows": "spent",
        "fields": [
          "aliases": [
            "domain": [
              "items": ["max": 240, "min": 1, "type": "string", "unit": "bytes"],
              "maxItems": 5,
              "type": "array",
            ],
            "kind": "lww",
            "writer": "server",
          ],
          "equipment": [
            "domain": [
              "enum": ["barbell", "dumbbell", "machine", "cable", "bodyweight", "kettlebell"],
              "type": "string",
            ],
            "kind": "const",
            "writer": "client",
          ],
          "name": [
            "domain": ["type": "string"],
            "kind": "lww",
            "max": 240,
            "min": 1,
            "unit": "bytes",
            "writer": "client",
          ],
          "pattern": [
            "domain": ["enum": ["squat", "hinge", "press", "pull", "carry", "core", "isolation"], "type": "string"],
            "kind": "const",
            "writer": "client",
          ],
          "stepKg": [
            "domain": ["max": 99.99, "min": 0.01, "quantum": 0.01, "type": "number"],
            "kind": "const",
            "writer": "client",
          ],
        ],
        "idPattern": "^[A-Za-z0-9_-]{1,64}$",
        "idSpace": "global",
        "identity": "minted",
        "life": true,
        "mint": [
          "alphabet": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
          "length": 16,
          "prefix": "",
        ],
        "origins": ["replica", "server"],
        "primary": true,
        "revivable": false,
        "scope": "product:gym",
        "seeded": ["ordinalMax": 99999, "seedMax": 58],
        "type": "exercise",
      ],
      [
        "fields": [
          "aliases": [
            "domain": [
              "items": ["max": 240, "min": 1, "type": "string", "unit": "bytes"],
              "maxItems": 5,
              "type": "array",
            ],
            "kind": "lww",
            "writer": "server",
          ],
          "name": [
            "domain": ["type": "string"],
            "kind": "lww",
            "max": 240,
            "min": 1,
            "unit": "bytes",
            "writer": "client",
          ],
        ],
        "identity": "keyed",
        "key": ["ref": "exercise"],
        "life": false,
        "origins": ["replica", "server"],
        "scope": "product:gym",
        "type": "exerciseName",
      ],
      [
        "deadRows": "spent",
        "fields": [
          "closedBy": ["domain": ["enum": ["finish", "stale"], "type": "string"], "kind": "lww", "writer": "server"],
          "displayName": [
            "domain": ["nullable": true, "type": "string"],
            "kind": "lww",
            "max": 240,
            "unit": "bytes",
            "writer": "server",
          ],
          "finishedAt": ["domain": ["integer": true, "min": 0, "type": "number"], "kind": "lww", "writer": "server"],
          "historyRoutineId": [
            "domain": ["nullable": true, "pattern": "^[A-Za-z0-9_-]{8,64}$", "type": "string"],
            "kind": "const",
            "writer": "server",
          ],
          "plan": ["domain": ["nullable": true, "type": "json"], "kind": "const", "writer": "server"],
          "routineId": [
            "domain": ["nullable": true, "type": "id"],
            "kind": "lww",
            "ref": "routine",
            "writer": "server",
          ],
          "startedAt": ["domain": ["integer": true, "min": 0, "type": "number"], "kind": "lww", "writer": "server"],
        ],
        "idPattern": "^[A-Za-z0-9_-]{8,64}$",
        "idSpace": "global",
        "identity": "minted",
        "life": true,
        "mint": [
          "alphabet": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
          "length": 16,
          "prefix": "",
        ],
        "origins": ["replica", "server"],
        "primary": true,
        "revivable": false,
        "scope": "product:gym",
        "seeded": ["ordinalMax": 99999, "seedMax": 58],
        "type": "session",
      ],
      [
        "deadRows": "spent",
        "fields": [
          "completedAt": ["domain": ["integer": true, "min": 0, "type": "number"], "kind": "lww", "writer": "client"],
          "exerciseId": ["kind": "const", "ref": "exercise", "writer": "client"],
          "kind": [
            "domain": ["enum": ["warmup", "working", "drop", "failure"], "type": "string"],
            "kind": "lww",
            "writer": "client",
          ],
          "note": ["domain": ["type": "string"], "kind": "lww", "max": 4000, "unit": "bytes", "writer": "client"],
          "reps": [
            "domain": ["integer": true, "max": 500, "min": 1, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
          "rpe": [
            "domain": ["max": 10, "min": 1, "nullable": true, "quantum": 0.1, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
          "sessionId": ["kind": "const", "parent": true, "ref": "session", "writer": "client"],
          "setNumber": ["kind": "serial", "serialNext": ["sessionId", "exerciseId"], "writer": "server"],
          "weightKg": [
            "domain": ["max": 500, "min": -500, "quantum": 0.01, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
        ],
        "idPattern": "^[A-Za-z0-9_-]{8,64}$",
        "idSpace": "global",
        "identity": "minted",
        "life": true,
        "mint": [
          "alphabet": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
          "length": 16,
          "prefix": "",
        ],
        "origins": ["replica", "server"],
        "primary": true,
        "revivable": false,
        "scope": "product:gym",
        "seeded": ["ordinalMax": 99999, "seedMax": 58],
        "type": "set",
      ],
      [
        "cap": 10,
        "deadRows": "spent",
        "fields": [
          "body": ["domain": ["type": "string"], "kind": "lww", "max": 500, "unit": "bytes", "writer": "client"],
          "ord": ["domain": ["type": "fracKey"], "kind": "lww", "writer": "client"],
          "title": [
            "domain": ["type": "string"],
            "kind": "lww",
            "max": 60,
            "min": 1,
            "unit": "chars",
            "writer": "client",
          ],
        ],
        "idPattern": "^[A-Za-z0-9_-]{8,64}$",
        "idSpace": "global",
        "identity": "minted",
        "life": true,
        "mint": [
          "alphabet": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
          "length": 16,
          "prefix": "",
        ],
        "origins": ["replica", "server"],
        "primary": true,
        "revivable": false,
        "scope": "product:gym",
        "seeded": ["ordinalMax": 99999, "seedMax": 58],
        "type": "note",
      ],
      [
        "deadRows": "spent",
        "fields": [
          "kg": [
            "domain": ["max": 400, "min": 20, "quantum": 0.01, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
          "recordedAt": ["domain": ["integer": true, "min": 0, "type": "number"], "kind": "lww", "writer": "client"],
        ],
        "idPattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "identity": "keyed",
        "life": true,
        "origins": ["replica", "server"],
        "primary": true,
        "scope": "product:gym",
        "type": "weighin",
        "wholePut": true,
      ],
      [
        "fields": [
          "confirmHaptic": ["default": true, "domain": ["type": "boolean"], "kind": "lww", "writer": "client"],
          "confirmSound": ["default": false, "domain": ["type": "boolean"], "kind": "lww", "writer": "client"],
          "restSeconds": [
            "default": .null,
            "domain": ["integer": true, "max": 900, "min": 15, "nullable": true, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
          "restSound": ["default": true, "domain": ["type": "boolean"], "kind": "lww", "writer": "client"],
          "units": [
            "default": "kg",
            "domain": ["enum": ["kg", "lb"], "type": "string"],
            "kind": "lww",
            "writer": "client",
          ],
        ],
        "idPattern": "^prefs$",
        "identity": "singleton",
        "life": false,
        "origins": ["replica", "server"],
        "scope": "product:gym",
        "singletonId": "prefs",
        "type": "prefs",
      ],
      [
        "deadRows": "spent",
        "fields": [
          "agent": ["domain": ["type": "string"], "kind": "const", "max": 64, "unit": "chars", "writer": "client"],
          "changes": [
            "domain": [
              "items": [
                "properties": [
                  "after": [
                    "properties": [
                      "restSeconds": ["integer": true, "max": 900, "min": 15, "type": "number"],
                      "sets": [
                        "items": [
                          "properties": [
                            "reps": ["integer": true, "max": 100, "min": 1, "type": "number"],
                            "weightKg": ["max": 500, "min": -500, "quantum": 0.01, "type": "number"],
                          ],
                          "type": "object",
                        ],
                        "maxItems": 20,
                        "type": "array",
                      ],
                    ],
                    "type": "object",
                  ],
                  "before": [
                    "properties": [
                      "restSeconds": ["integer": true, "max": 900, "min": 15, "type": "number"],
                      "sets": [
                        "items": [
                          "properties": [
                            "reps": ["integer": true, "max": 100, "min": 1, "type": "number"],
                            "weightKg": ["max": 500, "min": -500, "quantum": 0.01, "type": "number"],
                          ],
                          "type": "object",
                        ],
                        "maxItems": 20,
                        "type": "array",
                      ],
                    ],
                    "type": "object",
                  ],
                  "exerciseId": ["pattern": "^[A-Za-z0-9_-]{1,64}$", "type": "string"],
                  "kind": ["enum": ["kept", "added", "removed", "retargeted"], "type": "string"],
                ],
                "required": ["kind", "exerciseId"],
                "type": "object",
              ],
              "maxItems": 100,
              "type": "array",
            ],
            "kind": "const",
            "writer": "client",
          ],
          "connection": [
            "domain": ["type": "string"],
            "kind": "const",
            "max": 128,
            "unit": "bytes",
            "writer": "client",
          ],
          "door": ["domain": ["enum": ["ask", "mcp"], "type": "string"], "kind": "const", "writer": "client"],
          "intent": ["domain": ["enum": ["revise", "remove"], "type": "string"], "kind": "const", "writer": "client"],
          "proposedName": [
            "domain": ["type": "string"],
            "kind": "const",
            "max": 240,
            "unit": "bytes",
            "writer": "client",
          ],
          "routineId": ["kind": "const", "ref": "routine", "writer": "client"],
          "settledAt": ["domain": ["integer": true, "min": 0, "type": "number"], "kind": "lww", "writer": "server"],
          "state": [
            "default": "pending",
            "kind": "ranked",
            "rank": ["applied": 1, "dismissed": 1, "pending": 0, "superseded": 1],
            "writer": "server",
          ],
          "summary": ["domain": ["type": "string"], "kind": "const", "max": 400, "unit": "bytes", "writer": "client"],
          "supersededBy": [
            "domain": ["pattern": "^[A-Za-z0-9_-]{8,64}$", "type": "string"],
            "kind": "lww",
            "writer": "server",
          ],
          "threadId": [
            "domain": ["nullable": true, "pattern": "^[A-Za-z0-9_-]{8,64}$", "type": "string"],
            "kind": "lww",
            "writer": "server",
          ],
        ],
        "idPattern": "^[A-Za-z0-9_-]{8,64}$",
        "idSpace": "global",
        "identity": "minted",
        "life": true,
        "mint": [
          "alphabet": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz",
          "length": 16,
          "prefix": "",
        ],
        "origins": ["replica", "server"],
        "revivable": false,
        "scope": "product:gym",
        "seeded": ["ordinalMax": 99999, "seedMax": 58],
        "type": "proposal",
      ],
    ],
    "version": 4,
  ]
}
