// Generated by SyncSchemaGen from packages/api-contract/sync/journal.registry.json. Do not edit.

import SyncCore

public enum Journal {
  public static let scope = ScopeRef.product("journal")

  public enum Types {
    public static let page = "page"
    public static let journalState = "journalState"
  }

  public enum Commands {
    public static let savePage = "journal.savePage"
    public static let claimPage = "journal.claimPage"
  }

  public enum Codes {
    public static let claimConflict: RefusalCode = "claim-conflict"
  }

  public enum Defaults {
    public enum JournalState {
      public static let firstPage: String = "pending"
      public static let placeholder: String = "pending"
      public static let privacyLine: String = "pending"
      public static let scales: String = "pending"
    }
  }

  static let registryFile: JSON = [
    "commands": [
      [
        "args": [
          "body": ["domain": ["type": "string"], "type": "json"],
          "day": ["type": "ref<page>"],
          "energy": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "type": "json",
          ],
          "mood": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "type": "json",
          ],
          "source": ["domain": ["enum": ["typed", "spoken"], "type": "string"], "type": "json"],
          "stamp": [
            "domain": [
              "properties": [
                "actor": ["max": 64, "type": "string", "unit": "bytes"],
                "counter": ["integer": true, "max": 4294967295, "min": 0, "type": "number"],
                "ms": ["integer": true, "max": 9007199254740991, "min": 0, "type": "number"],
              ],
              "required": ["ms", "counter", "actor"],
              "type": "object",
            ],
            "type": "json",
          ],
        ],
        "name": "journal.savePage",
        "origins": ["replica", "server"],
        "predicts": ["page"],
        "scope": "product:journal",
        "serverInternal": false,
      ],
      [
        "args": [
          "body": ["domain": ["type": "string"], "type": "json"],
          "claimId": ["domain": ["max": 128, "min": 1, "type": "string", "unit": "bytes"], "type": "json"],
          "day": ["type": "ref<page>"],
          "energy": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "type": "json",
          ],
          "mood": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "type": "json",
          ],
          "source": ["domain": ["enum": ["typed", "spoken"], "type": "string"], "type": "json"],
        ],
        "name": "journal.claimPage",
        "origins": ["replica", "server"],
        "predicts": ["page"],
        "scope": "product:journal",
        "serverInternal": false,
      ],
    ],
    "minVersion": 4,
    "products": [
      "journal": [
        "codes": ["claim-conflict"],
        "device": [
          "contentClock": [
            "keyPattern": "^contentClock$",
            "localOnly": true,
            "value": [
              "properties": [
                "counter": ["integer": true, "max": 4294967295, "min": 0, "type": "number"],
                "ms": ["integer": true, "max": 9007199254740991, "min": 0, "type": "number"],
              ],
              "required": ["ms", "counter"],
              "type": "object",
            ],
          ],
          "pendingClaim": [
            "keyPattern": "^pendingClaim:[A-Za-z0-9_-]{1,128}$",
            "localOnly": true,
            "value": ["type": "json"],
          ],
        ],
        "surfaces": ["web", "ios"],
      ],
    ],
    "registry": "journal",
    "types": [
      [
        "fields": [
          "body": ["kind": "text", "max": 131072, "unit": "bytes", "writer": "server"],
          "documentStamp": [
            "domain": [
              "properties": [
                "actor": ["max": 64, "type": "string", "unit": "bytes"],
                "counter": ["integer": true, "max": 4294967295, "min": 0, "type": "number"],
                "ms": ["integer": true, "max": 9007199254740991, "min": 0, "type": "number"],
              ],
              "required": ["ms", "counter", "actor"],
              "type": "object",
            ],
            "kind": "lww",
            "writer": "server",
          ],
          "energy": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "kind": "lww",
            "writer": "server",
          ],
          "mood": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "kind": "lww",
            "writer": "server",
          ],
          "source": ["domain": ["enum": ["typed", "spoken"], "type": "string"], "kind": "lww", "writer": "server"],
        ],
        "idPattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "identity": "keyed",
        "life": false,
        "origins": ["replica", "server"],
        "primary": true,
        "scope": "product:journal",
        "type": "page",
        "visibleWhen": ["body", "mood", "energy"],
      ],
      [
        "fields": [
          "firstPage": [
            "default": "pending",
            "kind": "ranked",
            "rank": ["pending": 0, "retired": 1],
            "writer": "client",
          ],
          "placeholder": [
            "default": "pending",
            "kind": "ranked",
            "rank": ["pending": 0, "retired": 1],
            "writer": "client",
          ],
          "privacyLine": [
            "default": "pending",
            "kind": "ranked",
            "rank": ["pending": 0, "retired": 1],
            "writer": "client",
          ],
          "scales": ["default": "pending", "kind": "ranked", "rank": ["pending": 0, "retired": 1], "writer": "client"],
        ],
        "idPattern": "^journalState$",
        "identity": "singleton",
        "life": false,
        "origins": ["replica", "server"],
        "scope": "product:journal",
        "singletonId": "journalState",
        "type": "journalState",
      ],
    ],
    "version": 4,
  ]
}
