// Generated by SyncSchemaGen from packages/api-contract/sync/journal.registry.json. Do not edit.

import SyncCore

public enum Journal {
  public static let scope = ScopeRef.product("journal")

  public enum Types {
    public static let page = "page"
  }

  static let registryFile: JSON = [
    "commands": [],
    "minVersion": 1,
    "products": ["journal": ["surfaces": ["web", "ios"]]],
    "registry": "journal",
    "types": [
      [
        "fields": [
          "body": ["kind": "text", "max": 131072, "unit": "bytes", "writer": "client"],
          "energy": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
          "mood": [
            "domain": ["integer": true, "max": 10, "min": 0, "nullable": true, "type": "number"],
            "kind": "lww",
            "writer": "client",
          ],
          "source": ["domain": ["enum": ["typed", "spoken"], "type": "string"], "kind": "lww", "writer": "client"],
        ],
        "idPattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$",
        "identity": "keyed",
        "life": false,
        "origins": ["replica", "server"],
        "primary": true,
        "scope": "product:journal",
        "type": "page",
        "visibleWhen": ["body", "mood", "energy"],
      ],
    ],
    "version": 1,
  ]
}
