// Generated by SyncSchemaGen from packages/api-contract/sync/composition.json. Do not edit.

import SyncCore

public enum SyncSchema {
  public static let registry = try! Registry(name: "windmill", composing: [
    Registry(json: Gym.registryFile),
  ])
  public static let version = registry.version
}
