// Generated by SyncSchemaGen from the product registries in packages/api-contract/sync. Do not edit.

import SyncCore

public enum SyncSchema {
  public static let registry = try! Registry(name: "windmill", composing: [
    Registry(json: Gym.registryFile),
    Registry(json: Journal.registryFile),
  ])
  public static let version = registry.version
}
