import React from 'react';
import {
  GitBranchPlus,
  Sparkles,
  Sprout,
  Play,
  Ruler,
  Sofa,
  Palette,
  Lock,
  Plus,
  Trash2,
  Pencil,
  Star,
  MoreHorizontal,
  Users,
  Zap,
  Map,
  Info,
  Flag,
  Check,
  ZoomIn,
  ZoomOut,
  Maximize,
  X,
  ExternalLink,
  Archive,
  BookOpen,
  Camera,
  ClipboardCheck,
  Compass,
  Droplet,
  Flame,
  Gift,
  Grid3x3,
  Hammer,
  HardHat,
  Image as ImageIcon,
  Lamp,
  Layers,
  LayoutGrid,
  Library,
  Move,
  Package,
  PaintRoller,
  Paintbrush,
  Plug,
  ShoppingCart,
  Speaker,
  Sun,
  Thermometer,
  Truck,
  Tv,
  Wallet,
  Wifi,
  Shield,
  Share2,
  Leaf,
  Anchor,
  Feather,
  Gem,
  Crown,
  Moon,
  Cloud,
  Mountain,
  Unlock,
  Minus,
  Activity,
  Bell,
  Pin,
  RotateCcw,
  ArrowRight,
  Keyboard,
} from 'lucide-react';

// Icons are referenced by kebab name (`icon={<Icon name="chevron-down" />}`), backed by an explicit
// registry of named Lucide imports rather than the whole set. Add one by importing it above and
// registering its kebab name here.
const REGISTRY = {
  'git-branch-plus': GitBranchPlus,
  sparkles: Sparkles,
  sprout: Sprout,
  play: Play,
  ruler: Ruler,
  sofa: Sofa,
  palette: Palette,
  lock: Lock,
  plus: Plus,
  'trash-2': Trash2,
  pencil: Pencil,
  star: Star,
  ellipsis: MoreHorizontal,
  'more-horizontal': MoreHorizontal,
  users: Users,
  zap: Zap,
  map: Map,
  info: Info,
  flag: Flag,
  check: Check,
  'zoom-in': ZoomIn,
  'zoom-out': ZoomOut,
  maximize: Maximize,
  x: X,
  'external-link': ExternalLink,
  archive: Archive,
  'book-open': BookOpen,
  camera: Camera,
  'clipboard-check': ClipboardCheck,
  compass: Compass,
  droplet: Droplet,
  flame: Flame,
  gift: Gift,
  'grid-3x3': Grid3x3,
  hammer: Hammer,
  'hard-hat': HardHat,
  image: ImageIcon,
  lamp: Lamp,
  layers: Layers,
  'layout-grid': LayoutGrid,
  library: Library,
  move: Move,
  package: Package,
  'paint-roller': PaintRoller,
  paintbrush: Paintbrush,
  plug: Plug,
  'shopping-cart': ShoppingCart,
  speaker: Speaker,
  sun: Sun,
  thermometer: Thermometer,
  truck: Truck,
  tv: Tv,
  wallet: Wallet,
  wifi: Wifi,
  shield: Shield,
  share: Share2,
  leaf: Leaf,
  anchor: Anchor,
  feather: Feather,
  gem: Gem,
  crown: Crown,
  moon: Moon,
  cloud: Cloud,
  mountain: Mountain,
  unlock: Unlock,
  minus: Minus,
  activity: Activity,
  bell: Bell,
  pin: Pin,
  'rotate-ccw': RotateCcw,
  'arrow-right': ArrowRight,
  keyboard: Keyboard,
};

export function Icon({ name, size = 16, strokeWidth = 2, color = 'currentColor', style }) {
  const Cmp = REGISTRY[name];
  if (!Cmp) {
    if (import.meta.env?.DEV) console.warn(`[Icon] Unregistered icon: "${name}" — add it to Icon.jsx`);
    return null;
  }
  return <Cmp size={size} strokeWidth={strokeWidth} color={color} style={style} />;
}

export default Icon;
